### ISSUE TITLE
PGF complains it needs LuaTeX for "graph drawing" library

### ISSUE THREAD

**Issue by ararunaufc** [tectonic-typesetting/tectonic#1018]
Hello, everybody.

I'm trying to use tectonic to build a `beamer` document full of TikZ pictures. The code was ported from a previous version where I was using LuaTeX and building automatically with the "LaTeX Workshop" VSCode extension.

The problem I get is this error:

```text
error: pgflibrarygraphdrawing.code.tex:22: Package pgf Error: You need to run LuaTeX to use the graph drawing library.
```

Is there a way to work around this, or am I really stuck with using LuaTeX?

Thank you.

**Comment by kpym** [comment]
@ararunaufc I'm afraid you'll have to use LuaLaTeX if you want to use some of the algorithms (written in Lua because it's too complicated and slow to do it in TeX) in TikZ's graph library. 

My advice is, if you are not using beamer animations on those graphs, put those images in separate `standalone` files that you compile with `lualatex`. And then you can import the resulting pdf and compile the beamer with the compiler of your choice, for example `tectonic`.

**Comment by ararunaufc** [comment]
> @ararunaufc I'm afraid you'll have to use LuaLaTeX if you want to use some of the algorithms (written in Lua because it's too complicated and slow to do it in TeX) in TikZ's graph library.

That's too bad... 😞 I really wanted to switch to Tectonic 😢 

> My advice is, if you are not using beamer animations on those graphs, put those images in separate `standalone` files that you compile with `lualatex`. And then you can import the resulting pdf and compile the beamer with the compiler of your choice, for example `tectonic`.

That's actually great advice. Thanks.

Now that I think of it, I remember seeing something in the `beamer` docs that could be used to enable even figures with "animation". I just have to figure out how to use it right... 😕
