### ISSUE TITLE
using fonts downloaded by tectonic

### ISSUE THREAD

**Issue by drdv** [tectonic-typesetting/tectonic#1019]
`tectonic` downloads required packages while processing a document. I wonder whether there is a way for another tool to use the downloaded fonts (in particular). My use case is described at: https://github.com/mgieseki/dvisvgm/issues/237#issue-1650872950

**Comment by vlasakm** [comment]
AFAIK `.dvi` files unfortunately only list the base name of the font files (e.g. `font.otf` and not `/path/to/font.otf`), so after Tectonic (or XeTeX) is done, dvisvgm has to look up the files again. This by they way risks different files getting used for the layout part and for the dvisvgm rendering part (because metrics would be taken by Tectonic from different file than), but also as you noticed, the files may be not even found.

A simple solution might be for Tectonic to serialize full paths to fonts into `.xdv` files, dvisvgm is likely already handling absolute paths correctly. Unfortunately after a quick look it seems that the original information gets lost quite early on and keeping it longer is probably going to be a very instrusive change.

Another solution might be to make dvisvgm use Tectonic's file searching. Maybe this could be done by exposing the kpathsea interface in a library calling into Tectonic?

I am afraid I don't have a solution at the moment, though I might be overlooking something.
