### ISSUE TITLE
tex to pdf without accessing the file system

### ISSUE THREAD

**Issue by juliusernesti** [tectonic-typesetting/tectonic#1046]
# In-memory pdf generation with custom documentclass

We are looking for an engine that compiles latex source file into a pdf and have found this library. We could not figure out how to use a custom `.sty` file.

## Requirements

* In memory transformation without access to the file system
* Use of a custom document class and graphics (`.sty` and `.pdf` files)
* Perfomance

How can we use the `tectonic` crate to achieve this?

**Comment by pkgw** [comment]
Hi,

I think Tectonic should be perfect for your needs! To use something like a custom `.sty` file in your build process without filesystem access, though, you may not be able to use the [`tectonic::driver::ProcessingSession`] type, since it doesn't currently offer the ability to provide in-memory "files" like you want.

[`tectonic::driver::ProcessingSession`]: https://docs.rs/tectonic/latest/tectonic/driver/struct.ProcessingSession.html

The way things currently stand, I'd recommend starting with the code in [`src/driver.rs`] and stripping out all of the features that you don't need, which is probably most of them. To add the functionality that you're looking for, I think you ought to just be able to insert some data into the `MemoryIo` I/O layer around [here][1] as all of the driver state is assembled.

[`src/driver.rs`]:  https://github.com/tectonic-typesetting/tectonic/blob/master/src/driver.rs
[1]: https://github.com/tectonic-typesetting/tectonic/blob/master/src/driver.rs#L1089

It would definitely be reasonable to add some new APIs to the mainline crates if they would make your implementation easier (i.e., reduce the amount of necessary code duplication). In particular, it might make sense to provide to add a way to "add" new files to the MemoryIo layer in the ProcessingSessionBuilder. But I do think that this stock implementation expects to touch the filesystem in enough places that it won't meet your needs. It might be interesting to provide a `memdriver` module that is designed for completely in-memory needs. (I could see this being useful for WASM-type environments?)

**Comment by juliusernesti** [comment]
Hi,
thanks for the quick response.
Adding the files to `MemoryIo` is working. Adding an API for that would be great, as we don't need to fork and change the repository.
