### ISSUE TITLE
Font specified in .sty file not working

### ISSUE THREAD

**Issue by sporkl** [tectonic-typesetting/tectonic#1079]
Hello,

I'm very new to LaTeX and Tectonic, so apologies if anything I write here is missing something basic. I have a .sty file which I'm trying to apply to a document, and while it does seem to load the .sty file (the .sty file defines some commands which I use without issue in the .tex file), it does not seem to properly apply the fonts and formatting specified in the .sty file.

As far as I can tell, this appears to be a Tectonic-specific thing as Overleaf seems to handle these files as expected.

Here is a zip with the relevant files. Tectonic's output is suffixed with -tectonic, and the expected output is suffixed with -expected.
[isqcmc2023_latex.zip](https://github.com/tectonic-typesetting/tectonic/files/12470466/isqcmc2023_latex.zip)

I am on macOS 12.5.1, running Tectonic 0.14.1 installed through conda-forge. The font in question is Times, which for some reason seems to show up in most apps which allow font selection, but doesn't show up in Font Book.

Thank you!

**Comment by pkgw** [comment]
Hmm. If the font isn't showing up in Font Book for you, that might mean that it's not findable by the standard system mechanisms, which could cause Tectonic to be unable to load it and use it in your document.

If you have a basic document like this:

```
\documentclass{article}
\usepackage{times}
\begin{document}
Blah blah blah.
\end{document}
```

... does that seem to get rendered in the Times font, or not?

**Comment by sporkl** [comment]
It looks like that does not get rendered with the Times font. I was under the impression that `\usepackage{times}` included the font data itself, but I guess that's wrong?

Thanks for the help and apologies for the trouble!

**Comment by Dzordzu** [comment]
@sporkl can you close the issue? ;)

**Comment by sporkl** [comment]
Yep, sorry

**Comment by pkgw** [comment]
This might indicate that we need to patch our version of the `times` package to be able to locate a Tectonic-bundled version of the Times font. The Tectonic bundle almost surely contains this font (I mean, it's Times New Roman), but the font-finding portion of the engine is currently a bit limited where we need to load such fonts by explicitly specifying their filenames, and a lot of the standard TeXLive packages aren't set up that way — they instead identify fonts by their symbolic names (e.g. `Times New Roman`).

https://github.com/tectonic-typesetting/tectonic-texlive-bundles/pull/10 gives an example of such a patch. The diff against the upstream `fontawesome.sty` isn't explicit, but if I remember correctly, it might be as simple as adding a `.otf` in the definition of `\FA`.

In the longer term, it would be possible to extend Tectonic's bundle system to be able to index fonts by their symbolic names, so that this kind of discovery can happen automatically. That would be a bit more work, and would be a bit of a pain to implement right now since that font-discovery code is still written in C++.

**Comment by sporkl** [comment]
I do see the Times New Roman (but not Times) font in font book, does that mean this package should have worked?

**Comment by sporkl** [comment]
Small update: if I switch to using the newtx package, which seems to be the recommended way to include a lot of fonts including Times, everything seems to work properly.

**Comment by pkgw** [comment]
Thanks, that is a helpful piece of information!
