### ISSUE TITLE
tectonic::latex_to_pdf: \today command prints Thursday 1st January, 1970 

### ISSUE THREAD

**Issue by aleksandr-vin** [tectonic-typesetting/tectonic#1107]
I've found that `\today` command is not working correctly. Should print current day.

**Comment by vlasakm** [comment]
This is the result of the small scope of `tectonic::latex_to_pdf`, which doesn't allow any customizations. Thus you get a lot of defaults, one of which is that the build date is set to Unix epoch. This is because Tectonic aims at reproducibility, and the time 0 is an obvious choice for a reproducible time.

Should you wish to set the build date yourself, you need a Tectonic interface that allows customizations. See the [driver ](https://docs.rs/tectonic/latest/tectonic/driver/index.html) documentation. Starting with the implementation of `tectonic::latex_to_pdf` is the most straightforward way. You would need to do something like this to use the current time (losing reproducibility in the process):

```diff
@@ -162,6 +162,7 @@ pub fn latex_to_pdf<T: AsRef<str>>(latex: T) -> Result<Vec<u8>> {
             .primary_input_buffer(latex.as_ref().as_bytes())
             .tex_input_name("texput.tex")
             .format_name("latex")
+            .build_date(std::time::SystemTime::now())
             .format_cache_path(format_cache_path)
             .keep_logs(false)
             .keep_intermediates(false)
```

**Comment by Neved4** [comment]
For myself, I don't find an issue getting the current day with:
```latex
\documentclass{article}

\begin{document}
  \today
\end{document}
```

**Comment by vlasakm** [comment]
@Neved4 Compiling with the normal `tectonic` command produces the current date, since the underlying `tectonic` library is used differently in the wrapper command.

To reproduce this, you need to use [Tectonic's Rust API](https://docs.rs/tectonic/latest/tectonic/).

To reproduce, clone the tectonic repository to `/path/to/tectonic` and then something like this:

```
$ cargo new test-1107
$ cd test-1107/
$ cargo add --features external-harfbuzz --path /path/to/tectonic
$ cat > src/main.rs << EOF
> use std::io::Write;

fn main() {
    let latex = r#"
    \documentclass{article}
    \begin{document}
    \today
    \end{document}
    "#;

    let output = tectonic::latex_to_pdf(latex).expect("processing failed");
    std::fs::File::create("out.pdf").expect("create failed").write_all(&output).expect("write failed");
}
EOF
$ cargo run
```

Then see `out.pdf` with and without the patch above. 

Compiling with external harfbuzz is just my preference (faster compile time) and not related to this issue.

**Comment by Neved4** [comment]
@vlasakm Thanks much for the additional context!

**Comment by ratmice** [comment]
Interesting that `ProcessingSessionBuilder::create` appears to directly use `SystemTime::UNIX_EPOCH` directly, rather than `build_date_from_env` which also reads the `SOURCE_DATE_EPOCH` env var, even when `force_deterministic`.  Not sure if that is intentional, but changing that behavior would be one way to keep using `latex_to_pdf` while being able to adjust the date.
