### ISSUE TITLE
 LNCS template not compile

### ISSUE THREAD

**Issue by CRAG666** [tectonic-typesetting/tectonic#1117]
I tested the template with xelatex in overleaf and it compiles without problems when trying to compile in tectonic it is not possible to compile it.
https://www.springer.com/gp/computer-science/lncs/new-latex-templates-available/15634678

**Comment by vlasakm** [comment]
Can you please provide a [MWE](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that?noredirect=1&lq=1)?

I was able to compile the example from Overleaf ("View source") with Tectonic 0.14.1. The only thing I had to do was to not include `fig1.eps` (because I didn't have that file and `.eps` files would anyways be problematic with modern TeX engines like XeTeX and consequently Tectonic).

It seems that a particular template based on LLNCS class doesn't have XeTeX support and hence didn't work with Tectonic: https://github.com/tectonic-typesetting/tectonic/issues/494. But the `llncs` class seems to work fine in Tectonic.
