### ISSUE TITLE
Documentation: curly quotes

### ISSUE THREAD

**Issue by rm-dr** [tectonic-typesetting/tectonic#1124]
This is a minor issue :grin:.

I've noticed that the tectionic book often has unicode curly quotes (`“”`) instead of the quotes one finds on most keyboards (`""`). Should we fix this? This leads to ugly inconsistent formatting as more people edit the docs.

**Comment by pkgw** [comment]
I add the curly quotes manually (my Linux environment has a "Compose key" configuration that makes this easy) since the last time I checked, the Markdown processor didn't auto-curlify them properly ... and for a typesetting package, we want to be high-end about this kind of thing!

That being said, beyond the specifics of the quotation marks, the inconsistent formatting is something that would be nice to address. What bothers me a *lot* more than curly quotes is that I strongly prefer hard linewraps in the Markdown text, while most contributors seem to use soft wraps. I just merge such contributions as-is since (IMO) it's not worth going back and forth with people about linewrapping, but I don't like the inconsistency.

The "obvious" solution would be to use some kind of Markdown (re)formatter. I'm not aware of any such tool, but it feels like the kind of thing that probably exists? Whether any pre-existing tool is opinionated enough to normalize quotation marks, I don't know.

On another track, it's probably worth checking whether current mdbook applies smart quotes to turn straight quotation marks into curly ones. If it does, for the specific issue raised here, I think that it would make sense to normalize curly quotes in the source into straight ones.

**Comment by rm-dr** [comment]
Seems it does, see `output.html.curly-quotes` at https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options
