### ISSUE TITLE
microtype `testls` command does not work

### ISSUE THREAD

**Issue by cgahr** [tectonic-typesetting/tectonic#1128]
The `textls` command of the microtype package does not work.

Consider the following document:
```latex
% test.tex
\documentclass[12pt, a4paper]{article}

\usepackage{microtype}

\begin{document}
\textls[100]{this should work}
\end{document}
```

`$ pdflatex test.tex$`:
![grafik](https://github.com/tectonic-typesetting/tectonic/assets/26804763/37d3524a-fb34-4e2f-907c-e5aea96483c1)

`$ tectonic test.tex -Z continue-on-errors`:
![grafik](https://github.com/tectonic-typesetting/tectonic/assets/26804763/6e364221-68e9-47ce-bfde-0c8ea93220b6)
```
❯ tectonic test.tex -Z continue-on-errors
Running TeX ...
error: test.tex:6: Package microtype Error: Letterspacing currently doesn't work with xetex.
                                                                                                       
See the microtype package documentation for explanation.
Type  H <return>  for immediate help
warning: errors were issued by the TeX engine, but were ignored; use --print and/or --keep-logs for details.
Running xdvipdfmx ...
Writing `test.pdf` (3.26 KiB)
Skipped writing 1 intermediate files (use --keep-intermediates to keep them)
```

**Comment by rm-dr** [comment]
What happens if you compile that with xetex?

Judging by that error, I'd assume that microtype doesn't work with xetex (which is what tectonic uses)

**Comment by Neved4** [comment]
Hey @cgahr great catch! 💙

I can reproduce: when using XeTeX/tectonic the `\textls`[^1] macro doesn't work, as @rm-dr pointed out. Sadly, this is the expected behaviour now, and it may change in the future when `microtype` adds support for it.[^2]

In general you'd want to use `LetterSpace` and `WordSpace` to have a document compatible across pdfTeX/XeTeX/LuaTeX/tectonic.

[^1]: Note that `\textls` might break small caps when not using `SmallCapsFeatures={Letters=SmallCaps}` with `fontspec`.
[^2]: `microtype`'s manual specifies that `\textls` only works with pdfTeX/LuaTeX at the moment.   
  See [§7 Letterspacing revisited, ***`pdfTeX 1.40 | LuaTeX 0.62`***](https://osl.ugr.es/CTAN/macros/latex/contrib/microtype/microtype.pdf).

**Comment by cgahr** [comment]
That is sad to here, it was used in an external beamer-template.

However, something like `\newcommand{\textls}[2][1]{\addfontfeature{LetterSpace=40em plus.1em minus.1em} #2}` was a sufficient workaround for my use-case. Thank you very much for the pointer! 

If you want to reopen this issue open for tracking purposes, please do so, from my side, it can be closed.
