### ISSUE TITLE
unable to open input HTML template

### ISSUE THREAD

**Issue by Guelakais** [tectonic-typesetting/tectonic#1139]
I was trying to compile my project as pdf and html and had some problems. It's related to a [template](https://gitlab.com/latex4774305/thm_beamer_tectonic_template) I was working on. I simply tried to include several outputs in my tectonic.toml:
```
[doc]
name = 'THM_tectonic_template'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'beamer_pdf'
type = 'pdf'

[[output]]
name= 'beamer_html'
type= 'html'
```
The associated PDF output compiled correctly. Unfortunately, the html output didn't. I got the following output:
```
tectonic -X build
note: "version 2" Tectonic command-line interface activated
Running TeX ...
Rerunning TeX because "beamer_pdf.aux" changed ...
Running xdvipdfmx ...
warning: Tectonic does not support `config' special. Ignored.
Writing `/home/deck/projects/latex/THM_tectonic_template/build/beamer_pdf/beamer_pdf.pdf` (98.24 KiB)
Skipped writing 5 intermediate files (use --keep-intermediates to keep them)
Running TeX ...
warning: index.tex:10: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:11: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:13: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:17: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:31: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:40: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:54: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:55: Underfull \hbox (badness 10000) has occurred while \output is active
Rerunning TeX because "beamer_html.nav" changed ...
warning: index.tex:10: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:11: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:13: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:17: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:31: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:40: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:54: Underfull \hbox (badness 10000) has occurred while \output is active
warning: index.tex:55: Underfull \hbox (badness 10000) has occurred while \output is active
warning: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running spx2html ...
warning: imbalanced tags; had to close 0 to find `div`
error: unable to open input HTML template ``
caused by: not found
```
To be honest, this is the first time I've ever tried to compile a .tex into .html, because I thought it just wouldn't work. The Tectonic documentation said it was possible, so I tried it. Do I need to include anything? What am I missing here?

**Comment by pkgw** [comment]
It is possible, but the Tectonic HTML output framework is *extremely* specialized, and won't work with generic inputs. The input document needs to set a lot of special magic variables to not error out in the way that you're observing. Maybe the documentation needs to be modified to be more clear about that.

The only existing users of the HTML output mode are [tt-weave](https://github.com/tectonic-typesetting/tt-weave/), which translates the XeTeX literate programming source into an HTML book, and a prototype called [tectonopedia](https://github.com/tectonic-typesetting/tectonopedia) that aims to one day be the Tectonic reference encyclopedia. And tt-weave needs updating to work with the latest iteration of the HTML output support in the engine.

I'm going to close this issue since in its context the response is basically "no, HTML output doesn't actually work". But if you're interested in digging into this topic I am glad to discuss further!
