### ISSUE TITLE
Allow switching TeX Engine

### ISSUE THREAD

**Issue by HaoZeke** [tectonic-typesetting/tectonic#158]
I'm sorry if this seems trivial, but I have some documents which will only compile with `pdflatex`.

Is there any way to specify this? `tectonic` attempts to use XeLaTeX by default..

**Comment by PHPirates** [comment]
I only discovered tectonic myself very recently, but from the looks of it it is a latex engine itself - so an _alternative_ for pfdlatex or xetex. I do have had someone tell me that it's a fork of xetex, which would make sense.
Note the difference with software like TeX Live and MikTeX which mainly are there to handle installation of packages, which tectonic does automatically for you :)

**Comment by HaoZeke** [comment]
Ah well, I guess it's not a good fit for me yet.

Since I typically have archlinx install the `texlive-full` package.

This would be epic on windows though.

**Comment by MaxNoe** [comment]
The documentatio says it's *using* `xelatex`. So at least the possibility to switch to `lualatex` would be very nice.

**Comment by peterjc** [comment]
I just tried tectonic via ``conda install -c conda-forge tectonic`` and was surprised to find it does not provide the ``pdflatex`` executable.

**Comment by pkgw** [comment]
Sorry, I didn't realize that I never responded to this thread.

I'm afraid that I haven't figured out a way to clearly explain what Tectonic is doing, because this issue is proceeding from a bit of a misconception. Tectonic uses the source code of `xelatex` as a foundation, but it is a completely self-contained engine — it does not provide `pdflatex` or `xelatex` or any of those commands. It aims to supersede them. If you're using Tectonic, you will be running `tectonic file.tex` rather than `pdflatex file.tex` or `xetex file.tex` or `lualatex file.tex` or anything else.

As such, it's simply not possible to "switch the TeX engine" since Tectonic *is* the TeX engine. However, it is possible to modify Tectonic to be compatible with a broader range of documents. While the core TeX language has been stable for a very very long time, some documents rely on features introduced in newer engines. In particular, Tectonic can have problems with documents aimed at `pdf(la)tex` because that engine is not completely compatible with `xe(la)tex`. The intention is for Tectonic to stay as close to XeTeX as possible, but I have made a few changes that at least try to prevent it from crashing when passed a document intended to be processed with `pdftex`.

**Comment by pkgw** [comment]
I should add: so, @HaoZeke, if you have a document that fails to compile because of a `pdflatex`-ism, please report a separate issue, ideally narrowing down to the particular command causing problems. I don't think all such issues will be fixable, but in at least some cases it should be possible to add a workaround that will get such documents compiling on Tectonic.

**Comment by peterjc** [comment]
So if I aliased ``pdflatex`` (etc) to point at ``tectonic``, it might just work? If so, I could see advantages in offering wrappers for this (especially if they need to set any extra options for quirks modes to match the older command line tools).

**Comment by pkgw** [comment]
@peterjc It should work if you don't provide any extra command-line arguments. I have made a very distinct choice for the program to change the command-line user experience in ways that are totally incompatible with the traditional programs, though, so I don't think it would be appropriate to provide standard aliases.

**Comment by JonasOlson** [comment]
@pkgw:
> As such, it's simply not possible to "switch the TeX engine" since Tectonic _is_ the TeX engine.

Ah, thanks, I needed this clarification. Now, does Tectonic aim to supersede LuaLaTeX as well, or will LuaLaTeX have features outside the scope of Tectonic?

**Comment by pkgw** [comment]
Well, "supersede" probably isn't the right word. Each project will have its own strengths and weaknesses, and the best choice is going to depend on one's particular needs. I certainly exclusively use Tectonic and so it supersedes LuaLaTeX for my purposes, but YMMV.

From another angle: Tectonic was launched without consultation of the XeTeX or LuaLaTeX developers (or anyone else) and it is certainly not "blessed" by any of these projects the way that (as I understand it) LuaLaTeX is with regards to pdftex.
