### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by alexreg** [tectonic-typesetting/tectonic#2]
I just stumbled across this project, and was very pleased to find it indeed! I managed to get it building and running on my system, though it would be great with some examples, and I really think that would help get people more interested in your project.

In any case, I'd be glad to lend a hand with this project, if you feel it could help. Perhaps you have something that could be worked on largely independently? Maybe some example programs, for a start. Just let me know, and I can work on a PR.

**Comment by alexreg** [comment]
(Another idea: perhaps proper build script for dependencies, though I'm not sure how much of that you want to leave to the system and its package manager.)

**Comment by pkgw** [comment]
Thanks for the positive feedback!

Tectonic is currently in a "soft launch" mode so there are definitely still some rough edges with the setup. But I think that the project is just about ready for early usage and so I have been working hard on smoothing things out. For instance, I have created [a GitHub organization](https://github.com/tectonic-typesetting) and am working on setting up a simple website for users.

**I would love help on this front!** Some more exampel programs would be great. You are also right that the dependencies need work. (For instance, [we don't build on docs.rs right now](https://docs.rs/crate/tectonic/0.1.0/builds).) I have been reluctant to tackle that since there are a *lot* of dependencies but they need to be dealt with at some point. (My initial plan for providing binary packages is to use the [conda-forge](http://conda-forge.github.io/) project as a base; [see here](https://anaconda.org/pkgw-forge/tectonic/).)

**Comment by pkgw** [comment]
https://tectonic-typesetting.github.io/ !

**Comment by pkgw** [comment]
Also, I am about to transfer this repository over to the new tectonic-typesetting GitHub organization. Would love to add more contributors!

**Comment by alexreg** [comment]
Okay, sounds great. Shall we create an issue that lists some issues, with checkboxes, and priorities? Or maybe separate issues, so we can take advantage of the GitHub tagging system? Then I could tackle one or two perhaps, and help you out.

I don't quite get the motivation behind conda-forge, if I'm honest. Is it some sort of cross-platform package manager? To be honest, getting it installed and built on Mac right now isn't too hard, and a Homebrew formula could be created for tectonic in the future, though I don't know about other platforms so much.

**Comment by pkgw** [comment]
Yes, I was planning to create a few issues tagged with "beginner-friendly" or something like that to try show people how they might contribute.

Yes, `conda` is exactly a cross-platform package manager. It's developed by [Continuum Analytics](http://www.continuum.io/) as the basis of their scientific Python distribution system. It might not be that well-known outside of the scientific community but it is nice because it is cross-platform, has an open package build infrastructure, and allows unprivileged users to install and manage their software packages. It seems like a good way to go to me since Tectonic depends on libraries that you can't count on users having installed: poppler, freetype, graphite2, harfbuzz, etc.

**Comment by alexreg** [comment]
Beginner-friendly issues would be great! Even more advanced ones, if you like. I'll try to create some too.

Hmm, I've had a look at *conda*, and personally I'm not a big fan. I can definitely see the motivation for it, but the fact that another big dependency (conda itself, and all of its dependencies like Python) is dragged in is a big downside, for me. I think I would leave the build/install process for dependencies manual for *tectonic* developers, but have OS-specific packages for tectonic (e.g. Homebrew, dpkg, REM) that pull in the requisite dependencies. This would certainly be the more traditional way. Maybe some contrib scripts for developers that pull in the dependencies would be useful however. Anyway, all this is just my suggestion; as it's your project, you're obviously welcome to ignore it, and it shan't affect how I contribute. :)

**Comment by pkgw** [comment]
I guess that I think of it as being a hassle to provide OS-specific binaries, but with (1) Docker/Vagrant and (2) the fact that the installed Tectonic is literally only a single binary, it should be pretty easy to provide options in this case. Could you make an issue for adding OS packages for whichever format you're most interested in?

**Comment by alexreg** [comment]
Well, for Homebrew you don't even have to provide binaries, just build instructions; the pre-built binaries are generated for you. I think other package managers do similar things these days, to be honest.

**Comment by pkgw** [comment]
This was a very nice first issue to see! But let's call it solved for now 🥇
