### ISSUE TITLE
URL to the default config is broken

### ISSUE THREAD

**Issue by lembacon** [tectonic-typesetting/tectonic#200]
URL to the default config `https://purl.org/net/pkgwpub/tectonic-default` hardcoded [here](https://github.com/tectonic-typesetting/tectonic/blob/fcaf88c5e287952c6601b0f2443eba7226ac4077/src/config.rs#L29) is broken. It is redirected to `https://dl.bintray.com/pkgw/tectonic/tl2016extras/2016.0r4/tlextras-2016.0r4.tar` and then leads to a `403 Forbidden` HTTP status code.

**Comment by pkgw** [comment]
I just got an email from Bintray about rate-limiting my account, so I think this is an intentional choice by th e provider. I will investigate to see if the limitations can be lifted! If not we are going to need to switch to a backup. (Fortunately, the PURL.org redirect would make this transparent for existing installations.)

**Comment by lembacon** [comment]
Thanks for the clarification. :-)

**Comment by pkgw** [comment]
Working on it. In the meantime, I've uploaded the current files with another service. The bundle URL https://tectonic.newton.cx/bundles/tlextras-2016.0r4/bundle.tar should hopefully work. This can be activated either with the `-w` option to the command line program (if you're using version 0.1.8 — it was broken before) or by editing the default configuration file [as described here](https://tectonic.newton.cx/t/how-to-use-tectonic-if-you-can-t-access-purl-org/44).

**Comment by pkgw** [comment]
[Bit more info here on the forums](https://tectonic.newton.cx/t/web-service-outage-workaround-available/140).
