### ISSUE TITLE
Language identification

### ISSUE THREAD

**Issue by alexreg** [tectonic-typesetting/tectonic#3]
Oddly, GitHub seems to be identifying this project as using the C language, even though it is known to support identification of Rust. I presume you see the same at <https://github.com/tectonic-typesetting>.

**Comment by pkgw** [comment]
If you go by lines of code, I'm sure that identification is correct! There is a whole lot of code in the `tectonic/` source subdirectory. At this point the Rust is a relatively thin layer on the C/C++, and since Rust gives you much more "bang for the buck" per line of code I expect that will be true for a long time. So, I think this is fine.

**Comment by alexreg** [comment]
Ah, I didn't dig too deeply. Fair enough! I guess converting the C/C++ to Rust will be a gradual piecemeal process.
