### ISSUE TITLE
tectonic does't handle filenames with spaces

### ISSUE THREAD

**Issue by MrSpock** [tectonic-typesetting/tectonic#36]
When you try to use tectonic with file that contain spaces in filename (MacOS) this is happening:

```
 » tectonic file\ name\ with\ spaces.tex
note: this is a BETA release; report issues at https://github.com/tectonic-typesetting/tectonic/issues
Running TeX ...
note: indexing http://purl.org/net/pkgwpub/tectonic-default
note: resolved to https://dl.bintray.com/pkgw/tectonic/tl2016extras/2016.0r3/tl2016extras.tar
note: downloading SHA256SUM
error: something bad happened inside TeX; its output follows:

===============================================================================
===============================================================================

error: failed to open input file "file"
```

**Comment by alexander-bauer** [comment]
I've been able to reproduce this with a unit test on my fork, and I've been following through the code. I think a potential problem spot is [`tectonic/xetexini.c:2844-2889`](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetexini.c#L2844-L2889). I'm aiming to solve this if I can, and will open a pull request when I do.

**Comment by pkgw** [comment]
Yes, I think you're on the right track. The way that the initial filename gets fed into the engine is quite odd — see [this comment](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetexini.c#L4167-L4172). Thanks for writing a test case and investigating!

**Comment by alexander-bauer** [comment]
After some more tracking-down, I suspect the actual problem code may be in `scan_file_name` of [`tectonic/xetex0.c:10660-10680`](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetex0.c#L10660-L10680). Although this populates `cur_name` somehow, it's unclear to me exactly what `cur_name` is -- it doesn't appear to be a string of any form. Interpreted as a pointer, it leads away from the program address-space, and interpreted as the start of a buffer, it does not resemble a string.

**Comment by alexander-bauer** [comment]
More specifically, I am guessing that [`more_name`](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetex0.c#L10425) returns `false` when it first encounters a space. Setting `stop_at_space = false` inside `scan_file_name` gets it to process the whole string (I think), but yields
```
! Emergency stop
*** (job aborted, no legal \end found)
No pages of output.
Transcript written on ?.
```

**Comment by alexander-bauer** [comment]
I found the problem. The deep, dark internals of xetex expects the filename it's passed to be terminated with a space. In fact, that space is added [here](https://github.com/tectonic-typesetting/tectonic/blob/master/tectonic/xetexini.c#L2884), in the my original suspect code block.

The filename processor that expects the space actually handles quoting correctly, but we don't add any, so passing in filenames with literal quotes should probably work. However, since we're munging the string in `init_io()` anyway, we may as well quote the whole thing, since we know where it starts and stops.

Anyway, the result of all this is that we can process files with spaces, but all the tests are broken, because they expect the raw filename, and they're getting the filename enclosed in quotes.
