### ISSUE TITLE
Search for pre-installed tex dependencies

### ISSUE THREAD

**Issue by j-haj** [tectonic-typesetting/tectonic#42]
If this was a design decision I apologize for the noise. It seems Tectonic does not search for tex files that may already be installed on the system. It would be a more pleasant UX if Tectonic searched for any necessary files prior to downloading them as this would save time on initial use (on the order of seconds to minutes for me) and keep the installation size down.

**Comment by pkgw** [comment]
I see the appeal of this, but I believe that this is actually strongly incompatible with the fundamental Tectonic design.

One of the core goals of Tectonic is reproducibility. To that end, all of the LaTeX support files are stored in the large "bundle" file that's served over the internet. The bundle is (aims to be) fully self-consistent and is associated with a single content-derived cryptographic digest so that you know exactly what support files your document was compiled with.

If we start pulling in files from a random local TeX installation, we lose the power of being able to point to a single, specific source of the support files that were used to compile a document. The key is that the bundle is more like a Git repository than a big bag of files: each file is a piece of a single, versioned super-entity.

Now you can definitely imagine cases where it would be nice to leverage local files. If the standard bundle is missing a particularly obscure package, say, it might be nice to be able to slurp that file out of TeXLive and copy it into the document's directory. (That's the recommended way to overcome missing/busted files in the bundle.) But it's hard for me to see a tractable way to do this from a UX perspective.
