### ISSUE TITLE
Consider renaming project to a name that isn't trademarked commercial software

### ISSUE THREAD

**Issue by SEJeff** [tectonic-typesetting/tectonic#43]
[Tectonic](https://coreos.com/tectonic) is the name of a trademarked commercial product from CoreOS.

```
    Word Mark	TECTONIC
    Goods and Services	IC 009. US 021 023 026 036 038. G & S: Computer software, namely, software for developing, managing, updating, and maintaining online server instances and clusters hosted by third parties; computer operating system software; computer operating system software for distributed systems. FIRST USE: 20150406. FIRST USE IN COMMERCE: 20150406
    IC 038. US 100 101 104. G & S: Providing access to hosted computer operating systems and computer applications through the Internet; Peer-to- peer network computer services, namely, electronic transmission of audio, video and other data and documents among computers. FIRST USE: 20150406. FIRST USE IN COMMERCE: 20150406
    Standard Characters Claimed	
    Mark Drawing Code	(4) STANDARD CHARACTER MARK
    Serial Number	86560796
    Filing Date	March 11, 2015
    Current Basis	1A
    Original Filing Basis	1B
    Published for Opposition	December 22, 2015
    Registration Number	5013800
    Registration Date	August 2, 2016
    Owner	(REGISTRANT) CoreOS, Inc. CORPORATION DELAWARE 3043 Mission Stret San Francisco CALIFORNIA 94110
    Attorney of Record	Brian R. Coleman
    Type of Mark	TRADEMARK. SERVICE MARK
    Register	PRINCIPAL
    Live/Dead Indicator	LIVE
```

Courtesy of http://tmsearch.uspto.gov TESS search for Serial 86560796.

Note that I have nothing to do with CoreOS, but see this as a real problem. In US trademark law, you lose them if you don't defend them. Renaming is the only sensible thing IMO since the first commit for this project was 973289eaaaed067d0f704fb78fdef2c087977a6d on Nov 18, 2016, and this trademark was granted before then.

**Comment by PerBothner** [comment]
IANAL, but I'm pretty sure you can have multiple "things" with the same name, even multiple registered trademarks.  One factor is whether there is likely to be confusion between the things.  I don't think that is an issue in this case.

I run the [Kawa](http://www.gnu.org/software/kawa/) project.  At one time there was a reasonably-well regarded commercial IDE also called Kawa.  We knew about each other, but there was never a problem. (The IDE is now long-dead.)

Time to talk to a lawyer if/when CoreOS complains. Until then I wouldn't worry about it.

**Comment by j-haj** [comment]
I agree with @PerBothner , I think this is making something out of nothing. For example, consider Apple's Swift. Prior to the release of Swift there was another language called Swift along with a number of companies with Swift in the name. Everything seems to have turned out alright there.

**Comment by pkgw** [comment]
OK. This is definitely something that I take seriously and want to do right.

Based on my informal IANAL research (yay), I believe that it is appropriate and responsible to keep on using Tectonic as the name of this project. The main thing, in my interpretation, is that their project and this one are in just completely different domains — I don't see how any confusion between the two pieces of software is going to come up, especially in any kind of context that might harm CoreOS's commercial interests.

I have to admit that I very much like the current name, so the question in my mind is whether it a *preemptive* name change is advisable. Here are the three reasons I can come up with:

1. Not changing the name now puts project-associated people in some kind of legal risk
2. Someone wants to do something with the project that would clash with CoreOS's trademark much more directly.
3. A possible future name change will seriously harm the project.

I am not worried about (1). Clearly there's nothing malicious here, and we're not a commercial project.

I also have trouble seeing anything relevant to (2). Maybe if one wanted to start a Tectonic (typesetting) commercial support services company or something, but I certainly have no intentions in that direction and I would be shocked if anyone else did either.

As for (3), changing a project name is annoying, but happens all the time: e.g. MySQL ⇒ MariaDB. I prefer to cross that bridge if/when I come to it.

@j-haj Maybe not the best example since it's a bit easier to persuade people to play along when you have literally hundreds of billions of dollars that you can spend on lawyers if you want to ...

**Comment by pkgw** [comment]
Oh, I should add: thanks @SEJeff for bringing this up. Again, I do take these issues seriously, so it's good to be careful about them.

**Comment by pkgw** [comment]
Oh, one more item: this does depend a bit on what other internet not-a-lawyers think. If, say, Debian didn't want to distribute the project (even under a name like say `tectonic-typesetting`) due to trademark-related worries, that would be the sort of thing that would start making a rename look like the better option. But that is again a bridge to be crossed if/when we get there.
