### ISSUE TITLE
how do I cache resources needed to generate PDF output?

### ISSUE THREAD

**Issue by efx** [tectonic-typesetting/tectonic#430]
~~I plan to embed tectonic within a web service and use it to generate PDF's somewhat programmatically.~~
While running one batch I noticed the following error:
```
warning: open of input my-cool-document.aux failed
caused by: couldn't probe
caused by: unexpected HTTP response to URL https://archive.org/services/purl/net/pkgwpub/tectonic-default: 502 Bad Gateway
```
How can I use a local copy of this archive? Do I need to use `--web-bundle`? Can that be a local path, not just a URL?
This reminded me of #159 and other issues I've perused about the caching system tectonic uses for LaTeX packages.
I can add whatever answers here to #427.

**Comment by efx** [comment]
Due to how long the underlying dependencies take to generate the PDF, I found [pdfcpu](https://github.com/pdfcpu/pdfcpu) suits the use case for performantly adding a graphic to a batch of PDFs. So I do not plan to actually run the `tectonic` binary for processing a batch of documents.

**Comment by rekka** [comment]
At the moment, tectonic's default caching strategy might cause trouble when running it on a batch of documents.

Coincidentally, I just created a pull request #431 to improve the story here by caching the index and other data.

Tex likes to probe for files that likely do not exist (yet) like your `my-cool-document.aux`. Since tectonic does not cache the index of the online tar bundle, it has to download it first to check that `my-cool-document.aux` is not in there and report to the tex engine that the file does not exist. This leads to a lot of network traffic including probing `archive.org` on every run and it might cause for example `archive.org` to start dropping requests (I guess it might add a timeout to prevent denial-of-service attacks?).

See #85 for some discussion on why it is this way.  

There is the `--only-cached` command line option that prevents tectonic to try to fetch uncached files, but it only really works well if you are sure that all the necessary files from the online tar bundle are already cached. I.e., run tectonic on some of your files to make sure that all the required resources are cached, and then add `--only-cached` on further invocations.

**Comment by efx** [comment]
Ah, thank you for the added explanation rekka and work to improve the behavior.
> leads to a lot of network traffic including probing archive.org on every run and it might cause for example archive.org to start dropping requests (I guess it might add a timeout to prevent denial-of-service attacks?

I definitely observed the dropped requests while testing. It does sound considerate of the service to drop requests.
I'll try fiddling with the `--only-cached` and your PR to get a better understanding of what resources my document needs.

**Comment by efx** [comment]
Closing as @rekka's work accomplishes my underlying need. Thank you!
