### ISSUE TITLE
Need tests for the tar bundle and local cache code

### ISSUE THREAD

**Issue by rekka** [tectonic-typesetting/tectonic#433]
Currently `local_cache.rs` and `itarbundle.rs` has no test coverage. We should devise tests that check downloading files from http tar bundle and the local caching that would catch things like #432 . Not sure what the best approach would be.

**Comment by rekka** [comment]
I thought a bit about how to approach this. One option is for the test binary to launch a basic static file server on `localhost` serving a tiny tar bundle and have tectonic use it. Looking around for static file servers in rust, there's code like <https://github.com/weihanglo/sfz> (MIT licensed) that we could slim down to the bare minimum. But I do not have experience with testing network code. Is it OK to run such a server on a CI machine or Windows?

**Comment by pkgw** [comment]
@rekka Yes, that should definitely be OK, and I agree that it would be the right way to test this portion of the functionality.

Besides the example you found, I bet that there are a *lot* of sample static-file servers out there; it's a very common demo case. We could also look into whatever [zola](https://www.getzola.org/) uses for its `zola serve` functionality. And then there's the [Big list of http static server one-liners](https://gist.github.com/willurd/5720255) if you open up to considering other languages/frameworks ...

**Comment by rekka** [comment]
@pkgw You are right. I looked into it over the weekend and I could write a fully functional server for tectonic testing purposes using `hyper` that supports RANGE http requests in only about 50 lines of code. We can run it directly in the test binary on a separate thread while executing a tectonic session.

I used `zip2tarindex` from [tectonic-staging](https://github.com/tectonic-typesetting/tectonic-staging/) to create a dummy tar bundle and it seemed to basically work.

I am considering whether it makes sense to use the code `zip2tarindex` directly (as a library) in the testing binary to create a tar bundle in memory on the fly from `tests/assests` directory.

We also need to modify the local cache root to point it to a temporary directory so that we don't pollute the real cache. I have tried to do this using a hacky global variable (env variable) similarly to what tectonic already does for other tests, which again basically works.

I am gonna prepare a pull request with a prototype within a week or so (I hope...).

**Comment by pkgw** [comment]
Cool, I'm glad to hear that implementing a test server in Rust looks to be straightforward!

If we really want to exercise all of the client code, we probably do need to reuse the zip2tarindex code. So we should probably look into turning that into a published crate on crates.io.

Agreed that test code should use some kind of temporary cache directory. This seems like a feature that folks might want for more than just the test rig, so I'm open to ideas about the best way to expose that functionality. Can we re-use `TECTONIC_INTERNAL_TEST_ROOT` to indicate that a temporary cache should be used, or would the test binary have to be run with that variable unset in order to exercise the functionality correctly (as this are currently implemented)?

**Comment by rekka** [comment]
I created #441 with a working prototype.

Turns out that `zip2tarindex` is unnecessary since tectonic only reads the resource file content anyway and not the tar metadata.

I might look into reusing `TECTONIC_INTERNAL_TEST_ROOT` later. It does complex things.

**Comment by rekka** [comment]
Resolved in #441
