### ISSUE TITLE
header copyright comments are out of date 

### ISSUE THREAD

**Issue by efx** [tectonic-typesetting/tectonic#438]
I noticed the copyright headers list various years and year ranges:
```
$ rg -i 'Copyright .* the Tectonic Project'
src/io/format_cache.rs
1:// Copyright 2018 the Tectonic Project

src/io/stack.rs
2:// Copyright 2016-2017 the Tectonic Project

src/status/termcolor.rs
2:// Copyright 2017 the Tectonic Project
```

1. does this matter? Or should these list the initial year including the current year e.g. `Copyright 2017-2019 the Tectonic Project`?

If so we should probably automate that as a command to run periodically in development or by a bot.

**Comment by pkgw** [comment]
Amateur-hour internet lawyering time, but I *believe* that the current situation is actually correct. My understanding is that you update the copyright year if a work is updated/modified in that year, but not if it's unchanged. So e.g. if a file hasn't been touched since 2017, the copyright year should still be listed as 2017. The way I think about it is that you wouldn't say that The Matrix is currently "Copyright 1999-2019".

In my patches I try to update the copyright years of the files I'm modifying, but I'm not 100% careful about this, and I haven't been checking it in other people's PRs. So I'm sure that even if the above reasoning is correct, we probably have some oversights.

**Comment by efx** [comment]
Thanks for the explanation.
> In my patches I try to update the copyright years of the files I'm modifying, but I'm not 100% careful about this, and I haven't been checking it in other people's PRs. So I'm sure that even if the above reasoning is correct, we probably have some oversights.

We could eventually add a simple check as a git hook but that seems overkill at the moment. I can keep this open as a backlog task to consider automating a check as part of a CI validation step.

**Comment by efx** [comment]
I'm going to close this since I think a more accurate understanding of the problem and a given solution would be quite different from the original title and description.
