### ISSUE TITLE
Missing font in package `bbm`

### ISSUE THREAD

**Issue by knifecake** [tectonic-typesetting/tectonic#478]
I was trying out Tectonic on a project which uses the `bbm` package for some math symbols.

This is a minimal example that causes tectonic to fail, but works with pdfLaTeX (TexLive full 2018, revision 49885):

```tex
\documentclass{article}

\usepackage{bbm}

\begin{document}
This should work: $\mathbbm{1}$.
\end{document}
```

This  is the output I get with tectonic:

```
$ tectonic minimal.tex
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
Running xdvipdfmx ...
warning: Could not locate a virtual/physical font for TFM "bbm10".
warning: >> There are no valid font mapping entry for this font.
warning: >> Font file name "bbm10" was assumed but failed to locate that font.
error: Cannot proceed without .vf or "physical" font for PDF output...
```

I'm using Tectonic 0.1.11 (from Homebrew) on MacOS Sierra.

Thanks for sharing this really cool project!

**Comment by pkgw** [comment]
Thanks for the report! Apologies for taking a very long time to get back to you.

Does your example work with `xelatex`? That's the engine that Tectonic forks from, and it handles fonts differently than pdflatex.

**Comment by knifecake** [comment]
Thanks for your reply!

It does work with `xelatex` (XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018)).

**Comment by pkgw** [comment]
Ohhhkayy, finally looking into this one as I update to TeXLive 2020.

I am not sure if it will fully solve this problem, but in investigating it I have seen some evidence that suggests that we need to catch up to upstream XeTeX, cf. tectonic-typesetting/tectonic-staging#8. I was kind of hoping we could avoid confronting that, but I think we have to :-/ Once that is done, *hopefully* this will get fixed with the TL2020 update, but only time will tell.

**Comment by pkgw** [comment]
OK, I've identified what's going on here. The TeXLive 2020 update won't help, unfortunately. In the standard TeXLive stack, the PDF generation process automatically generates a "PK" font file from the requested BBM font, by launching an external program `mktexpk`. Tectonic isn't in a position to do that, leading to the missing-font problem.

We might be able to import the `mktexpk` program and fix this. I don't have a good sense as to how common of an issue it is or how hard it woud be to import the functionality.

**Comment by knifecake** [comment]
Thank you for taking the time to look at this! I'm sorry I can't be of more help since I'm only a LaTeX user. Personally, I only use the `1` character of the mathbb font very rarely and it can be easily replaced by something else, say `\mathbf{1}` so it is the biggest deal. Keep up the good work!

**Comment by ratmice** [comment]
not sure if you need to work with pdflatex (where this wont work), but an option that works with both xetex and tectonic is unicode-math.
```
\documentclass{article}
\usepackage{unicode-math}
\begin{document}
This should work: $𝟙$.
\end{document}
```

**Comment by pkgw** [comment]
Thanks all. I'm going to close this since I think this issue is best approached by something like @ratmice's solution. Feel free to comment and/or request a reopen if you think there's more to discuss here.

**Comment by ineol** [comment]
Is there a solution which does not imply changing the input tex file? I was trying to compile a document written by someone else when I hit the same error. 

```
Running xdvipdfmx ...
warning: Tectonic unable to generate PK font "bbm10" (dpi 600) on-the-fly
warning: Could not locate a virtual/physical font for TFM "bbm10".
warning: >> There are no valid font mapping entry for this font.
warning: >> Font file name "bbm10" was assumed but failed to locate that font.
error: Cannot proceed without .vf or "physical" font for PDF output...
```

Also, most publishers accept only files which compile with pdflatex so I need my files to stay compatible.

**Comment by pkgw** [comment]
Unfortunately, to support files like this without any changes, someone would need to do the work to add the needed features, like PK font generation, and that's probably not a small effort. But in principle it could happen. Due some pretty low-level differences in how XeTeX/Tectonic and pdflatex/lualatex handle fonts, however, there are some aspects that will probably never be able to be papered over.

If you're in control of the document source, that changes things a lot. If nothing else, you can use constructs like `\ifxetex` to more easily create a document that works on multiple TeX engines.

More broadly, I'd like to build up some documentation and code about how to create "portable" TeX code in the modern context — since TeX has a (deserved) reputation for portability I think that folks sometimes don't appreciate the way that compilation results can depend on the engine that you use. One of my goals is to get Tectonic creating excellent HTML output, which will only heighten the need for good information about which features are portable and which aren't.
