### ISSUE TITLE
LNCS compilation error

### ISSUE THREAD

**Issue by tathanhdinh** [tectonic-typesetting/tectonic#494]
Hello all,

I just start using `tectonic` today, sorry if this is a duplicate.

While compiling the sample file of `LNCS` [template](https://github.com/latextemplates/LNCS)

```bash
cd LNCS
textonic paper.tex
```

I've got the following error:

```bash
...
note: downloading microtype.sty
note: downloading microtype-xetex.def
note: downloading microtype.cfg
error: something bad happened inside TeX; its output follows:

===============================================================================
(paper.tex
LaTeX2e <2018-04-01> patch level 4
Babel <3.20> and hyphenation patterns for 84 language(s) loaded.
(llncs.cls
Document Class: llncs 2018/03/10 v2.20 
 LaTeX document class for Lecture Notes in Computer Science
(article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(size10.clo)) (multicol.sty) (aliascnt.sty (remreset.sty))) (babel.sty
(switch.def) (ngerman.ldf (ngermanb.ldf (babel.def (xebabel.def (txtbabel.def))
))) (english.ldf) (english.ldf)) (regexpatch.sty (expl3.sty (expl3-code.tex)
(l3xdvipdfmx.def)) (xparse.sty)) (ifluatex.sty) (cfr-lm.sty (xkeyval.sty
(xkeyval (xkvutils (keyval)))) (fontenc.sty (t1enc.def) (t1lmr.fd))
(textcomp.sty (ts1enc.def)) (nfssext-cfr.sty (svn-prov.sty) (ifthen.sty)))
(fontenc.sty (t1enc.def)) (inputenc.sty

Package inputenc Warning: inputenc package ignored with utf8 based engines.

) (graphicx.sty (graphics.sty (trig.sty) (graphics.cfg) (xetex.def)))
(upquote.sty) (booktabs.sty) (paralist.sty) (csquotes.sty (etoolbox.sty)
(csquotes.def) (csquotes.cfg)) (textcmds.sty) (microtype.sty
(microtype-xetex.def) (microtype.cfg))

! Package microtype Error: Disabling ligatures of a font is only possible
(microtype)                with pdftex version 1.30 or newer.
(microtype)                Ignoring \DisableLigatures.

See the microtype package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.149 ...leLigatures{encoding = T1, family = tt* }
                                                  
No pages of output.
Transcript written on paper.log.
===============================================================================

error: the TeX engine had an unrecoverable error
caused by: halted on potentially-recoverable error as specified
```

Many thanks for any help.

**Comment by pkgw** [comment]
Thanks for the report!

As best I can tell, the LNCS classfiles are designed to work with `pdflatex` or `lualatex`, but unfortunately not `xelatex`, from which Tectonic is derived. Normally the particular engine choice doesn't matter so much, but these files try to invoke some fancy font features, which is when the differences between the different packages start mattering. So, it looks like it would take some fiddling to get these files to work with Tectonic.

I can get `paper.tex` to compile with the following changes:

- Comment out `expansion=` setting in `microtype` RequirePackage
- Comment out the `DisableLigatures` command
- Replace all `ifluatex` with `ifxetex`
- Replace all `\set*font{Latin Modern *}` with a call to `'\usepackage{lmodern}`

Since all of the changes are in the `paper.tex` file, I'd say that it's a overly aggressive about using engine-specific features; there's nothing in `llncs.cls` that triggers any issues. Depending on your exact use case, that may or may not be very helpful.

**Comment by tathanhdinh** [comment]
@pkgw thank you.
