### ISSUE TITLE
Sync with XeTeX

### ISSUE THREAD

**Issue by khaledhosny** [tectonic-typesetting/tectonic#61]
I’m not sure what version (or git revision) of XeTeX was used as the base here, but it seems to miss some of the new fixes in XeTeX (e.g. some serious bugs in OpenType math have been fixed in the last cycle which seems to be missing here).

**Comment by pkgw** [comment]
Thanks for the heads-up. It's been a while since I've synced up with XeTeX sources.

And I also need to document how the syncing happens. It is possible to report exactly which version of XeTeX we track; we should do so.

**Comment by alexreg** [comment]
Hmm, does it not make to use a Git submodule for the XeTeX bits? This might make the job of syncing sources easier.

**Comment by Mrmaxmeier** [comment]
It looks like `441b4104a39b4df9ee64f2176d56ca7a451ef70c Fix non-portable use of MIN (replace with std::min) in XeTeXOTMath.` (2016-10-03)
is part of `tectonic/` while the child commit `02554b6fc8dc9a45d2740526f39761e4ba5d0f9f Migrate XeTeXOTMath to use new HarfBuzz API.` (2016-10-03) is not applied.

**Comment by pkgw** [comment]
Probably the `MIN` change is a case of convergent evolution, but not actually intentionally applying that specific patch.

I have recently fixed up the [staging repo](https://github.com/tectonic-typesetting/tectonic-staging) to use [Norbert Preining's public git mirror](http://git.preining.info/texlive/) of the TeXLive repo, as well as updating the scripts and explaining the process in more detail. So it should now be somewhat more feasible for people who aren't me to track the evolution of the reference codebase.

(@khaledhosny: BTW, I am tracking the XeTeX sources embedded in the TeXLive repo, rather than the ones hosted at SourceForge. As far as I can tell, they are quite similar, so I just went with TeXLive since the rest of the "staging" process requires that checkout. If you think it would be better to track SourceForge, please let me know.)

I have also updated the reference sources in the staging repo. The final step in the process — that I am studiously avoiding — is manually importing the changes (relative to the last time the sources were synced) into the main Tectonic codebase. There's a lot to go through (and of course the amount to deal with only increases with time ...).

Relatedly, in this case I don't think we want to use a submodule, because many aspects of the Tectonic C code are expected to slowly diverge from the XeTeX source as the codebase evolves in its own direction. We want to follow the *semantics* of changes to XeTex as much as possible, but their expression in code is going to look more and more different.

That being said ... if we add the staging repo as a submodule of the main repo, we then get a version-controlled reference to exactly which version of the reference code is being tracked in the transformed source. Which would be very nice to have! I'll look into that.

**Comment by pkgw** [comment]
Well, that took a while. But we are now pulled up to very recent TeXLive, namely Subversion revision 46289. There were a lot of changes but I *think* I ported everything correctly ... reassuring is that our TRIP test outputs became slightly closer to the ones of stock TeX!

Harfbuff OpenType Math layout goodness ahoy!

**Comment by khaledhosny** [comment]
Tracking TeX Live SVN should be good enough, it gets synced at least once a year before the release and should have stable XeTeX code
