### ISSUE TITLE
unreachable

### ISSUE THREAD

**Issue by burrbull** [tectonic-typesetting/tectonic#639]
https://github.com/tectonic-typesetting/tectonic/blob/64db8d70ebc76f5d5b29cb7d492e077621a1768f/tectonic/dpx-cidtype0.c#L213

**Comment by pkgw** [comment]
Thanks for the report! Agreed, the above statement is embedded in a for loop:

```
for (i = 0; i < vorg->numVertOriginYMetrics && gid > vorg->vertOriginYMetrics[i].glyphIndex; i++) {
```

From my read of the code, I'd guess that it should be `gid >= ...`

Looking at https://github.com/shirat74/dvipdfm-x/blob/master/cidtype0.c, which was updated within the past month, this issue is still present in the mainline xdvidpdfm-x sources. It should be reported upstream, although upstream sure doesn't make it easy ...
