### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by burrbull** [tectonic-typesetting/tectonic#692]
https://github.com/tectonic-typesetting/tectonic/blob/045dbb5350e6bdb33bbf89d01942add49a1484d4/tectonic/xetex-ini.c#L2534-L2535

As I can see `hash` point to not allocated memory? Is not it?

**Comment by pkgw** [comment]
Yes, that's correct. The `hash` array is always indexed by values that are at least as large as `hash_offset`, so no out-of-bounds memory is ever accessed. The TeX sources notes that some compilers require don't like this arrangement, though, and so you can set `hash_offset` to 0 if required. This just "wastes" an amount of memory equal to the first 514 (= `hash_offset`) records of the array.

I'm going to close this since it's not an actionable issue, but feel free to continue commenting.
