### ISSUE TITLE
Tweak the latex command?

### ISSUE THREAD

**Issue by teras** [tectonic-typesetting/tectonic#693]
When I use the minted package, I receive this error:
```
! Package minted Error: You must invoke LaTeX with the -shell-escape flag.
See the minted package documentation for explanation.
```
... which means that latex needs to be called with the `-shell-escape` option, or minted couldn't work.
Is there a way to change the given latex parameters?

**Comment by pkgw** [comment]
Hello,

This is the famous issue #38. Tectonic doesn't call latex; it *is* its own LaTeX engine. Tectonic has its a special I/O backend that at the moment doesn't support shell-escape operation. I'm open to adding support for it, but no one has sat down to do the implementation.

I'm going to close this issue since it's I believe redundant with #38. Please follow that issue, or comment here if you think this separate issue should be kept open.
