### ISSUE TITLE
Ability to specify TeX engine i.e. xelatex, pdflatex etc.

### ISSUE THREAD

**Issue by gsbabil** [tectonic-typesetting/tectonic#70]
The snippet below represents the preamble of a larger draft. It compiles fine with `pdflatex` (under TeX Live), but fails with `xelatex` due to [known incompatibility with the `breakurl` package](http://tex.stackexchange.com/questions/218196/breakurl-doesnt-work-with-xelatex). When compilation is attempted with `tectonic filename.tex`, it automatically picks `xelatex` which eventually leads to failed compilation.

- If there's a way to tell Tectonic which TeX engine it should use during compilation _i.e._ in this case I want `pdflatex`.

- How does Tectonic select which engine to use?

```
\documentclass{report}
\usepackage{hyperref}
\usepackage{breakurl}

\textwidth=1.5cm
\begin{document}
  \chapter{Introduction}
  \url{https://github.com/tectonic-typesetting/tectonic/issues/70}
\end{document}
```

**Comment by jtojnar** [comment]
Tectonic does not use any third party engine, it uses a custom fork of XeTeX.

**Comment by pkgw** [comment]
Yes, what @jtojnar said. Tectonic does not invoke other engines; it contains its own full engine that is derived from XeTeX. Several people have been confused on this point so it is something that the documentation and website need to be clearer about.

Seeing as the StackExchange page says that with XeTeX you just don't need to use the `breakurl` package, I am going to close this particular issue.

**Comment by cogumbreiro** [comment]
> Seeing as the StackExchange page says that with XeTeX you just don't need to use the 
`breakurl` package, I am going to close this particular issue.

@pkgw I just wanted to note that in some cases provided the user may be _forced_ to use `breakurl`. For instance, when the `documentclass` is the one using the offending package. In such a case, tectonic cannot be used.

**Comment by pkgw** [comment]
@cogumbreiro Good point. For reference, my vision is that in such cases we would basically customize the default bundle to remove the usage of `breakurl` in the documentclass in question, or potentially hack `breakurl.sty` to "defuse" the problematic parts. I want to minimize the amount of customization in the Tectonic bundle, but there is a lot of value to having Tectonic handle preexisting documents "well enough" without demanding customization.

**Comment by cogumbreiro** [comment]
That would be the ideal solution, @pkgw. Thank you for taking the time to clarify this.

For the sake of having a self-contained breaking example of what I was alluding to, the [Spring Nature document class](https://www.springernature.com/gp/authors/campaigns/latex-author-support) does not work with tectonic. 

```
\documentclass{sn-jnl}
\begin{document}
Hello world.
\end{document}
```

The output is:
```
$ tectonic sn-article.tex 
Running TeX ...
warning: algorithm.sty:11: 
Invalid UTF-8 byte or sequence at line 11 replaced by U+FFFD.
error: breakurl.sty:311: Undefined control sequence
error: halted on potentially-recoverable error as specified
```

Attachments: [`sn-jnl.cls`](https://github.com/tectonic-typesetting/tectonic/files/7571700/sn-jnl.cls.txt)

**Comment by vlasakm** [comment]
@cogumbreiro Thank you for the concrete example. Neither the Spring Nature class, nor the `breakurl` package are prepared to work with XeLaTeX. And there are many places where this can be fixed (I would prefer the class, but that is probably not going to happen).

In this particular case,  the class loads `breakurl` only if the `pdflatex` option is not passed to it. Since the option in this particular version of the class isn't used for anything else, we can also misuse the option as "don't load `breakurl` option:

```latex
\PassOptionsToClass{pdflatex}{sn-jnl}
\documentclass{sn-jnl}

\begin{document}
Hello world.
\end{document}
```

Note the difference between:

```latex
\PassOptionsToClass{pdflatex}{sn-jnl}
\documentclass{sn-jnl}
```

and:

```latex
\documentclass[pdflatex]{sn-jnl}
```

In the first case, the `pdflatex` option is passed only to the class. In the second case, the option is passed to every loaded package and (IIRC) subclasses. With such a generic option name, it's preferable not to use it globally, when we are not in fact `pdflatex`.

If we wrap the option passing conditional, we can achieve that the document will work with `latex+dvips` and with XeTeX / Tectoni.  (`breakurl` itself detects `pdftex` and doesn't do anything in that case).

```latex
\ifx\XeTeXversion\undefined\else
  \PassOptionsToClass{pdflatex}{sn-jnl}
\fi
\documentclass{sn-jnl}

\begin{document}
Hello world.
\end{document}
```

**Comment by cogumbreiro** [comment]
@vlasakm Those are good workarounds. Thank you very much for the detailed answer.

I was curious if either workaround would work with Tectonic, but it doesn't seem to like it. 

```
$ cat sn-article.tex
\PassOptionsToClass{pdflatex}{sn-jnl}
\documentclass{sn-jnl}

\begin{document}

Hello world.

\end{document}
$ tectonic sn-article.tex 
Running TeX ...
error: terminal input forbidden
```

I am unsure if the target audience of tectonic is academics, but I'll elaborate. When working in articles with multiple authors workarounds with conditional compilation are reasonable, such as the example above. Additionally, editors will compile the sources of the article to produce the final PDF using something other than tectonic. Having pdflatex compatibility would be a desirable feature in such a use case.

I am sorry for digressing, but I just wanted to thank you for this amazing and exciting piece of software! My research lab has been using Tectonic since version 0.3. We were also using tectonic in our CI/CD pipelines to trivially generate PDFs of the articles in progress. It's been a really valuable tool.

**Comment by vlasakm** [comment]
Hm, I proposed the workaround especially because I tested them with Tectonic `0.8.0` and current XeLaTeX, pdfLaTeX and LaTeX + dvips + ps2pdf.

@cogumbreiro can you pleaseshare the output of `tectonic -p sn-article.tex` and your tectonic version (`tectonic --version`)?

**Comment by cogumbreiro** [comment]
Oh, sorry I misunderstood your comment and thought it was just referring to XeLaTeX. I am using version `0.8.0`, updated this morning.

```
$ tectonic sn-article.tex 
Running TeX ...
error: terminal input forbidden
$ tectonic sn-article.tex --version
Tectonic 0.8.0
$ cat sn-article.tex 
\PassOptionsToClass{pdflatex}{sn-jnl}
\documentclass{sn-jnl}

\begin{document}

Hello world.

\end{document}
```

**Comment by vlasakm** [comment]
Can you also share the rather long output of `tectonic --print sn-article.tex`? AKA `tectonic -p sn-article.tex`?

**Comment by cogumbreiro** [comment]
Ah, thanks for that. In order to upload `sn-jnl.cls` I had to rename the file `sn-jnl.cls.txt` and I forgot to rename it back. Everything works now. Thank you @vlasakm for troubleshoot this. And, thank you again for the workaround for tectonic!

**Comment by vlasakm** [comment]
I am glad that it works!

I completly understand the need to be still compatible with "the old ways", hence the conditional option.

To explain myself a little bit: AFAIK for better or for worse, you can assume that Tectonic kind of _is_ XeLaTeX (although Tectonic may somewhat lag behind the newer XeLaTeX versions), thats why I kind of assumed that in my initial text.

**Comment by cogumbreiro** [comment]
Thank you for the clarification, that makes sense and does make tectonic very useful to many folks, I assume. This interchange has been really helpful and I am glad I can enjoy a sane UX while writing my papers.

**Comment by pkgw** [comment]
Thanks for the thoughtful discussion, folks! And I'm glad that you've found the software useful, @cogumbreiro . For what it's worth, I'm an academic and definitely want to target journal article workflows, but there's a tension because I also want Tectonic to make possible things that just can't be done with the existing tools — mainly, unbeatable HTML output. But the flip side of that goal is incompatibility with the other engines.
