### ISSUE TITLE
Auto-update tectonic-bin on AUR as part of release automation

### ISSUE THREAD

**Issue by oblitum** [tectonic-typesetting/tectonic#700]
Hi. I've commented this on AUR, but I'm afraid that maybe no one hears comments there as it seems the maintainer is automated, so I'm copying it here:

> Hi. This package is listed on the [Pre-built binary packages docs section](https://tectonic-typesetting.github.io/en-US/install.html#pre-built-binary-packages), but it's not a binary package. Sure, it's not a `-bin` package, but docs made me think otherwise, so I used yay to install it right away, and now it's still building on my low-end laptop....
>
> Will there be a `-bin` package?
>
> FWIW, the GitHub release assets does provide prebuilt binaries for Linux.

Rust packages on AUR often provide a  `-bin` version because Rust build can often be processor and time consuming.

**Comment by pkgw** [comment]
Thanks for reporting. I'm afraid that I'm not an Arch user and I'm not familiar with its packaging ecosystem, but I'm happy to merge any improvements to our automated system. @snowinmars recently submitted some updates in this area and might understand the relevant issues better?

**Comment by snowinmars** [comment]
Let me investigate it a bit.

**Comment by oblitum** [comment]
@snowinmars example Rust packages which provide `-bin` versions are, for example, `ytop-bin`, `zenith-bin`, `dust-bin`, etc.

**Comment by pkgw** [comment]
@oblitum OK, I am learning a bit about how this all works. I guess the basic thing is that our installation page is erroneous because I thought that our Arch package resulted in pre-built binaries. I thought that Arch Linux provided those? Is there a way to improve the existing package so that most users can obtain pre-built binaries using it? I can see how we could add a `-bin` package deriving from our official release artifacts (see discussion in #702) but there's no reason that we shouldn't be able to build Tectonic binaries within the Arch framework.

**Comment by oblitum** [comment]
>  I thought that Arch Linux provided those?

Not in such a way. The Arch Linux repositories are divided into two fields, [official repositories](https://wiki.archlinux.org/index.php/Official_repositories) (binaries), and AUR, which are completely user provided, non-official, not verified, these may or may not provide binaries, source version, or both.

> Is there a way to improve the existing package so that most users can obtain pre-built binaries using it?

If you want to go that route I think the best approach would make it into an official package under [community](https://wiki.archlinux.org/index.php/Official_repositories#community). For example, the [bat tool](https://github.com/sharkdp/bat), which is written in Rust, is present in the official community repositories: https://www.archlinux.org/packages/community/x86_64/bat/.

**Comment by oblitum** [comment]
Hey, I noticed there's a t[ectonic-bin package on AUR](https://aur.archlinux.org/packages/tectonic-bin) now, and I just installed it, so I guess it's time to close this issue. Thanks for your assistance.

**Comment by pkgw** [comment]
Yes, thanks to @lmartinez-mirror for creating the binary package! I would be happy to investigate systems to automate updating of the binary package when we make new releases, in the same way that we automatically update the non-binary package.

**Comment by lmartinez-mirror** [comment]
@pkgw Hi, please let me know what you need in order to automate the binary release's PKGBUILD.

**Comment by pkgw** [comment]
@lmartinez-mirror We need to set it up so that the release automation system can push to the `tectonic-bin.git` repository using its SSH key, the public half of which is stored in the repository [here](https://github.com/tectonic-typesetting/tectonic/blob/master/dist/arch/deploy_key.pub). I think that means that you need to add `tectonic-deploy <sasha+tectonic@hackafe.net>` as a package maintainer. Does that sound correct to you?

**Comment by lmartinez-mirror** [comment]
@pkgw That sounds about right. I've added `tectonic-deploy` as co-maintainer.

**Comment by pkgw** [comment]
@lmartinez-mirror I just put out a 0.4.1 release that attempted to auto-update the tectonic-bin package, and hopefully it has worked! Let me know if there seem to be any issues?

**Comment by lmartinez-mirror** [comment]
@pkgw Package builds successfully without issue.
