### ISSUE TITLE
Tectonic is not compatible with glossaries

### ISSUE THREAD

**Issue by AKuederle** [tectonic-typesetting/tectonic#704]
I was playing around with tectonic today and wanted to see if it could compile some PhD thesis documents from my department.
However, tectonic does not seem to support the glossaries package as it does not call `makeglossaries` after the first pdflatex run.

Is there any way to configure it to do it manually?

**Comment by pkgw** [comment]
Not yet, although there is work underway to make this sort of thing easier. (Namely, with #686 we can declare such stages in a `Tectonic.toml` file.)

At the moment the way that you'd implement something like this is to run Tectonic once with `--outfmt=aux`, run your external tool, then rerun Tectonic. With the `--hide` and `--makefile-rules` options you can even plug such an approach into a Make or Ninja framework and it will get all of the rebuild dependencies correct.

Tectonic actually bundles relatively small helper tools such as `bibtex`, but I see that `makeglossaries` is a Perl program, so that's not an option here, unfortunately.

**Comment by AKuederle** [comment]
Thank you very much for the fast reply! I tested you approach and that works well. Only downside is that I now can not rely on tectonic anymore to pull all dependencies, but need to manually install all required binaries.

After some more searching, I found another workaround for my specific problem. If your glossary is small enough, you can create it without index (Option 1 explained [here](https://www.dickimaw-books.com/latex/buildglossaries/)). This just requires Latex to be run twice. As this is done anyway in most cases, it will "just" work with tectonic.

**Comment by openscript** [comment]
@AKuederle Thank you for hinting an alternative solution. I used it successfully with a somewhat big document (150 pages).

`\makenoidxglossaries` instead of `\makeglossaries` and `\printnoidxglossary` instead of `\printglossary`

@pkgw I also tried to integrate it the way you suggested, but I didn't know where to start. Do you have a minimal example for this?

**Comment by Danacus** [comment]
@openscript I made added rudimentary support for `makeglossaries` based on the `biber` support, because I needed it. It works, but there's still room for improvement, such as support for `makeindex`.

See https://github.com/Danacus/tectonic/commit/946bc716431b3214af5ff61baff3c857c3263028

**Comment by thangleiter** [comment]
Thanks @Danacus, that works well enough! One instance where it does not work is when passing the `xindy` option to `glossaries`. But I guess that's not covered anyways because `makeindex` is not supported? 

Another point of improvement would be to run only if glossary is actually imported. Unfortunately I don't speak rust so wouldn't know where to start on that.
