### ISSUE TITLE
how do tectonic implement the "auto download" feature?

### ISSUE THREAD

**Issue by batkiz** [tectonic-typesetting/tectonic#717]
Thanks for this amazing software!

For some reasons(proxy and shell-escape), I have to use a *regular* LaTeX distribution. The distribution I use is [TinyTeX](https://github.com/yihui/tinytex), but it would often miss packages, so I really miss the auto-download feature in tectonic. So I'd like to make my own tool to get an *auto-download* experience for TinyTeX.

At first, I just extracted all the packages from `\usepackage[options]{pkg}`, `\RequirePackage[option list]{package name}[release date]` and `\RequirePackageWithOptions{package name}[release date]` command, and do a simple `tlmgr install <pkgs list>` (TinyTeX is based on TeX Live), but I met problems soon: the name in `\usepackage[options]{pkg}` is not the name `tlmgr install` use, for example, `graphicx` is a part of `graphics` package, I have to run `tlmgr install graphics` but not `tlmgr install graphicx` for this package.

In a word, I want to know how tectonic implements this feature. I tried reading the source code, but I'm not familiar with rustlang, can't find where it is :(

**Comment by pkgw** [comment]
Hello,

Tectonic has a lot of sophisticated infrastructure to make the auto-download feature possible. It is based on a fork of the XeTeX TeX engine, but with the I/O base layer replaced with Rust code that intercepts all of the I/O calls and requests to open files. When a request occurs for a file that isn't cached locally, the engine downloads the file from a pre-build "bundle" created from a TeXLive installation (code in [tectonic-texlive-bundles]).

[tectonic-texlive-bundles]: https://github.com/tectonic-typesetting/tectonic-texlive-bundles/

If you are using any engine besides Tectonic you won't be able to easily replicate this functionality, unfortunately. That's why I started Tectonic! But if it will work to go after the more modest goal of figuring out which TeXLive packages need to be installed to provide which style files, you should look into the TeXLive installation system and its package definitions. It should be possible to build up a reverse-map based on the TeXLive source repository.

**Comment by batkiz** [comment]
Thanks a lot! I will try to build up a reverse-map.
