### ISSUE TITLE
\today showing the wrong date on V2 cli

### ISSUE THREAD

**Issue by pineapplehunter** [tectonic-typesetting/tectonic#740]
Hello.
I was using the new Version 2 cli, and found that \today prints "January 1, 1970".
The older cli seemed to work just fine.

---

How to reproduce:
First create a new project.

```bash
$ tectonic -X new something
```

Add \today in document.

---

thanks!

**Comment by pkgw** [comment]
Yes, I just noticed this myself the other day. Not sure what the cause is but I expect this will be easy to fix.

Note, however, that it might take a bit longer than usual for the fix to make it into a release, because I have a lot of internal API changes in progress that will take a little while to work through responsibly.
