### ISSUE TITLE
User-configurable search path(s) for .sty files, etc. ("-Z searchpath=..."?)

### ISSUE THREAD

**Issue by jasonhan-vassar** [tectonic-typesetting/tectonic#755]
Hi, is there a recommended way to get Tectonic to locate my own .sty files when building (i.e., environment variable, flag, etc.)? My use case is with a "homework.sty" file that I'll be reusing in several documents in different locations, so copying the .sty multiple times doesn't seem like a great solution. Thanks for reading!

**Comment by aterenin** [comment]
Exact same situation. In TeX, the canonical way to do this is with `TEXINPUTS` and `BIBINPUTS`, which Tectonic does not currently seem to recognize.

Google and issue #108 seems to indicate this is currently unsupported, and I believe it is the single most important feature one could add for my use case. I'd love to switch to the package to avoid manually managing TeX Live - if this is an easy fix, happy to try to make a PR to add it.

**Comment by aterenin** [comment]
Looking a bit further, it seems the reason `TEXINPUTS` and `BIBINPUTS` are not currently supported is to maximize compilation reproducibility. This is a wonderful and worthy goal.

Therefore, following the discussion in #475, I propose to instead enable a command line argument marked "experimental" or "unstable" to discourage widespread use that either enables these variables to be read from the environment, or allows the user to pass them in as an additional command line argument. That way, users that need this have the capacity to make their setup work while not introducing needless barriers to reproducibility for everyone else. This solution would also handle #108.

**Comment by pkgw** [comment]
Yikes, it's taken me a while to reply to this straightforward inquiry. Sorry for that.

I'm biased, but I've gotten quite used to just copying around style files along the lines of your `homework.sty`. I keep some files in a Git repository and copy them out as needed.

If you're tracking your document source in Git, you could use Git submodules to automate the process a little bit more thoroughly.

As noted by @aterenin, I've been reluctant to add support for variables like `TEXINPUTS` directly because of its implications for reproducibility. I agree that some kind of unstable option like `-Z searchpath=...` would be a good compromise. Unlike the environment variable, it makes the customized build environment explicit with every run of the program. Now that the framework of #475 is in place, I think that adding such an option ought not require very much code.

I'm going to re-title this issue to make it more clearly refer to this particular aspect of things.
