### ISSUE TITLE
Tectonic depends on archive.org URL

### ISSUE THREAD

**Issue by rikhuijzer** [tectonic-typesetting/tectonic#765]
First of all, thank you for your work on tectonic. I'm a happy user, it saves many of my problems.

I would like to file an issue on the following. I'm running tectonic via Pandoc to generate a PDF in a CI job. Unfortunately, this job is a bit flaky since it can fail with
```
error: couldn't probe
caused by: unexpected HTTP response to URL https://archive.org/services/purl/net/pkgwpub/tectonic-default: 502 Bad Gateway
Error producing PDF.
```

which appears to come from

https://github.com/tectonic-typesetting/tectonic/blob/3e6fc3b811e7697056221b118f87bd2395c2ca13/src/config.rs#L194

and is a file of 2.6 GB. Of course, there might be very good reasons to download this dependency from archive.org. In that case, can I safely cache this thing myself (via the GitHub Actions cache)?

**Comment by pkgw** [comment]
Hi @rikhuijzer,

Due to the way that Tectonic manages its asset "bundles", I'm pretty sure that it won't work to cache the file yourself. Unfortunately I have never written clear documentation of how this system works (especially embarrassing for a technical documentation tool ...) so let me give you the gist here:

First, the specific `archive.org` URL serves as a programmable redirection. When I update the Tectonic asset bundles, I update this URL to point to the new version, and Tectonic users start getting new TeXLive assets. You will find that if you access it successfully, the `archive.org` URL currently redirects to a Microsoft Azure blob storage service.

The next thing is that the asset bundle is not just downloaded as one large file. The web-based bundles are made served in an "indexed tar" format: the main URL is a large `tar`-format file, and then there is also an `.index.gz` text file summarizing the locations of the various TeXLive assets within that large file. The Tectonic I/O layer uses HTTP range requests to download only subsets of the big tar file, never the entire thing.

Between these two factors, I would be surprised if it would work to try to have GitHub Actions cache the `archive.org` URL.

Now, something like a 502 Bad Gateway error from `archive.org` should be quite rare, but the service has been unfortunately flaky in the past. It is also inaccessible in China, so it is on my list to look into a replacement service.

In the meantime, there are at least a few existing GitHub Actions that use Tectonic, so you might look and see what they do. Once again, I'd hope that `archive.org` HTTP errors should be quite rare, but maybe people are working around the problem already.

**Comment by rikhuijzer** [comment]
> Once again, I'd hope that archive.org HTTP errors should be quite rare, but maybe people are working around the problem already.

Since opening this issue, I have run the action maybe one hundred times without issues, so it's not too big of a deal. The archive.org URL with a big file seemed unreliable to me, but I didn't think about whether it could actually be Azure blog storage and that not the full file is loaded each time.

Thank you for the extensive clarification. It sounds like a solid setup. I will close this issue.

**Comment by rikhuijzer** [comment]
> Once again, I'd hope that archive.org HTTP errors should be quite rare, but maybe people are working around the problem already.

For your information. Per week, I do about 20 runs and 2 fail. On some days, 4/5 runs fail due to bad gateway.

So, this is **not** a call for action on your side per se. The failures are annoying, but I'm still a happy Tectonic user :+1:

**Comment by rikhuijzer** [comment]
I've gone through a few more weeks of many CI runs. Some weeks, everything is perfect. However, on some days (like today), archive throws random 404 and internal server errors.

If archive.org is only meant to redirect to the Azure blob storage then it's probably more reliable redirect from an own domain. Something like <https://tectonic-typesetting.org/bundles> or <https://newton.cx/bundles>.

**Comment by rikhuijzer** [comment]
For a few hours now already:

```
$ curl -I https://archive.org/services/purl/net/pkgwpub/tectonic-default
HTTP/2 404
server: nginx/1.18.0 (Ubuntu)
date: Wed, 06 Oct 2021 20:28:46 GMT
strict-transport-security: max-age=15724800
```

**Comment by rikhuijzer** [comment]
Currently, the error is
```
error: unexpected HTTP response code 307 Temporary Redirect for URL https://archive.org/services/purl/net/pkgwpub/tectonic-default
Error producing PDF.
```

**Comment by pkgw** [comment]
I've merged in #832, so binaries built from master (or, shortly, the latest continuous-deployment release) should be functional again.

**Comment by rikhuijzer** [comment]
I'm afraid that I wasn't clear enough. #832 does indeed fix the absolute need for my patch. However, it is quite annoying in my workflow that archive.org fails a few times a week, because it is an unstable service. Specifically, my tests randomly fail in CI after 20+ minutes due to archive.org returning "service unavailable" etc.

So, thank you for the fix. That's great. At the same time, I will still keep using my patch to make CI more stable.

**Comment by pkgw** [comment]
OK, I'm starting to see requests come in to the new relay webservice already. So far so good ...

**Comment by rikhuijzer** [comment]
@pkgw to come back on this now after a few months. It's great! I've had **zero** failures related to this since the move. Thanks! :smile:
