### ISSUE TITLE
Worked on the first try

### ISSUE THREAD

**Issue by certik** [tectonic-typesetting/tectonic#768]
I needed to compile an older Beamer presentation on macOS, so I installed tectonic using Conda and it compiled my presentation on the first try without any errors and everything looks good. I've never used tectonic before.

Is Tectonic still in beta? It seems to work great.

Thank you for working on this.

**Comment by pkgw** [comment]
Thanks for the feedback! The Tectonic beta notice is admittedly pretty conservative: lots of people use Tectonic and it works reliably for them every day. But there are also lots of ways in which it could be even better, too. Another way to put it is that any "beta"-ness is more about missing features or possible changes to functionality, rather than the reliability of the functionality that's there.

Hope that helps, and thanks for using Tectonic!
