### ISSUE TITLE
`--keep-logs` ignores `max_print_line` environment variable and wraps at 79 characters

### ISSUE THREAD

**Issue by hugobuddel** [tectonic-typesetting/tectonic#809]
The LaTeX console output (the log) is by default wrapped at 79 characters. This limit can be [alleviated by setting the `max_print_line` environment variable](https://tex.stackexchange.com/a/1193/2775).

And indeed,
```
max_print_line=1048576 tectonic --keep-logs --print mylatexfile.tex
```
will print long messages. However, `mylatexfile.log` produced with the above command will have each line wrapped at 79 characters.

`pdflatex` will produce a log file with long messages.

Using Tectonic 0.4.1, which is not the latest.

This is not a particularly important issue, and my immediate problem is solved, so I'm mainly noting this inconsistency for reference. Feel free to close if it is not important enough to fix.

(I now redirect the output to a separate log file.  Which I subsequently grep for broken references, I missed some because the line break was exactly in the term I grepped for. Now I wonder whether there are things like LaTeX log parsers that make the logs easier to navigate.)

**Comment by pkgw** [comment]
Thanks for reporting! My general desire is to have Tectonic pay attention to as few environment variables as possible, since they're a form of invisible state that can make it hard to get reproducible results — I'm actually surprised that the stdout output is responsive to this variable. But I certainly agree that it would be helpful to have a way to avoid linewrapping in the log-file output. (To enable tool integrations I'd like to add a V2 command that's basically "run one pass and dump the contents of the specified intermediate file", so that I can e.g. integrate a tool that I have that automatically generates .bib based on the actual references in the document.)

As for your specific use case, FWIW I'd like to hack the LaTeX/bibtex infrastructure to report broken references through Tectonic's regular warning system so that one doesn't need to resort to this kind of thing anyway. TeX's default-verbose output is overall really bad for usability, IMO.

**Comment by hugobuddel** [comment]
It seems I was mistaken; tectonic entirely ignores `max_print_line`, as you expected.

I got confused because I first looked at the log and everything there was trimmed to 79 characters, but didn't pay close attention to the console output. Then I set `max_print_line` and saw that tectonic spits out many long lines on the console, but not in the log.

But it turns out that tectonic wraps all lines that end up in the log, but only some of the lines printed to the console. Without the variable set I only noticed the wrapped lines on the console, and the second time I only noticed the long lines. You see what you expect to see..

So I didn't actually solve my missing references-detection properly. Good to hear that you have thoughts on how that might be done through tectonic at a later stage!

I'll close this, because you are right that you should not introduce support for environment variables like `max_print_line`, it will only lead to problems down the road.
