### ISSUE TITLE
textbf not working when use pslatex package

### ISSUE THREAD

**Issue by dragove** [tectonic-typesetting/tectonic#815]
when pslatex package is included, fonts in textbf doesn't get bold.

**Comment by pkgw** [comment]
It might be possible to work around this, but in general, Tectonic (and XeTeX upon which it's based) create PDF files without any intermediate PostScript stage, so PostScript-related packages tend not to work well and/or cause problems, as you're seeing here.

This is symptomatic of a broader problem because it would be nice for Tectonic to succeed with documents written for other engines without requiring any customization, but I'm not sure how best to try to achieve that in the big picture. Can you avoid using `pslatex` in your case?

**Comment by dragove** [comment]
Oh, I forget to close this issue. I think it is working now.
