### ISSUE TITLE
package nicematrix does not work

### ISSUE THREAD

**Issue by japm48** [tectonic-typesetting/tectonic#818]
Here is a minimal example:
```latex
\documentclass{article}

\usepackage{nicematrix}

\begin{document}

\[
    \begin{bNiceArray}{rr}[]
     1 & 2 \\
     3 & 4
    \end{bNiceArray}
\]

\end{document}
```

It works with xelatex and fails in tectonic.

```
$ tectonic -k --keep-logs mv.tex
Running TeX ...
error: mv.tex:11: Fatal Package nicematrix Error: There is a problem. Maybe you have used l, c
(nicematrix)                      and r instead of L, C and R in the
(nicematrix)                      preamble of your environment.
(nicematrix)                      This error is fatal.

Type <return> to continue
Writing `mv.log` (11.91 KiB)
error: halted on potentially-recoverable error as specified
```

Output log: https://pastebin.com/h9PxrmKG
XeLaTex log (succesful run): https://pastebin.com/qP8VWsU8

**Comment by vlasakm** [comment]
I am not a nicematrix user, but this is my understanding:

This is due to use of different versions of the nicematrix package. Your XeLaTeX comes most likely from TeX Live 2021, which with the updates applied now has nicematrix version 6.1 (2021-08-20), but even the initial version of nicematrix in TeX Live 2021 (what your package manager might have installed) has 5.13 (2021-03-23). While tectonic ships with the initial TeX Live 2020, which has 3.14 (2020-03-23).

The [documentation](http://mirrors.ctan.org/macros/latex/contrib/nicematrix/nicematrix.pdf) says in the History section:

> Changes between versions 4.4 and 5.0
>  - Use of the standard column types l, c and r instead of L, C and R.

Presumably your problem would be fixed when tectonic updates to TeX Live 2021.

Until then, you may find success with putting a newer version of the `nicematrix.sty` file in your document's directory. The most recent one doesn't work, because it depends on a lot of the new stuff, but version 5.0 seems to work:

```
$ tectonic test.tex
Running TeX ...
error: test.tex:11: Fatal Package nicematrix Error: There is a problem. Maybe you have used l, c
(nicematrix)                      and r instead of L, C and R in the
(nicematrix)                      preamble of your environment.
(nicematrix)                      This error is fatal.

Type <return> to continue
$ curl -sLo nicematrix.sty 'https://git.texlive.info/texlive/plain/Master/texmf-dist/tex/latex/nicematrix/nicematrix.sty?id=5e7c45a283a2403c25348d1f470fed5654d78d63'
$ tectonic test.tex
Running TeX ...
Running xdvipdfmx ...
Writing `test.pdf` (4.42 KiB)
Skipped writing 1 intermediate files (use --keep-intermediates to keep them)
```

But there is probably a reason why there has been a lot of `5.x` point releases, so please read  the version history and update to newer version accordingly. I got the older version from Norbert Preining's git mirror of TeX Live, the history of the particular file is here: https://git.texlive.info/texlive/log/Master/texmf-dist/tex/latex/nicematrix/nicematrix.sty.

If someone with more tectonic experience knows a better solution, please share.

**Comment by japm48** [comment]
Thanks a lot!
It looks like a lot of issues I'm facing can be solved by updating to newer versions.
Are there plans on when is TeX Live 2021 supported? (not in a hurry, just wanted to know).

**Comment by pkgw** [comment]
Unfortunately there's no specific timeline ­— these updates are done when I get the chance to work on them, which is quite rare these days :-( *Hopefully* all that is needed for an update is to run through the steps described in the readme for the [tectonic-texlive-bundles](https://github.com/tectonic-typesetting/tectonic-texlive-bundles) repo, but often there are changes in the engine or tooling that need to be made in order for everything to work.

**Comment by mnrvwl** [comment]
Hello @japm48! I tried your MWE with `tectonic 0.11.0` and it works! We're using the 2022 bundle right now, give it a try and let me know how it works 💛

**Comment by japm48** [comment]
> Hello @japm48! I tried your MWE with `tectonic 0.11.0` and it works! We're using the 2022 bundle right now, give it a try and let me know how it works 💛

Thanks! I confirm this now works!

I'm closing this as fixed, as the MWE is now functional. If something more specific arises, a new issue may be opened instead.

PS: sorry for the delay, I was busy visiting another continent :)

**Comment by pkgw** [comment]
Thanks for following up this and so many other issues @mnrvwl, and thanks for confirming @japm48!
