### ISSUE TITLE
dvipng/dvisvgm not installed: is there a way to manually install packages?

### ISSUE THREAD

**Issue by shaunsingh** [tectonic-typesetting/tectonic#824]
Hi, I'm using the texlab server in vscode as well as org-preview-latex-fragment in emacs
Texlab requires dvipng for previews, org-preview-latex-fragment requires dvisvgm. 

Both editors complain about these packages missing from tectonic, However I can't figure out a way to install them. How can I go about doing this?

**Comment by ratmice** [comment]
I'm fairly certain that tectonic itself has no port of either dvipng, or dvisvgm. However these are merely executable utilities, so in theory I think it *should* work using the dvipng/dvisvgm utilities provided either by some other TeX distribution or OS distribution.
While i haven't tried it, it seems like DVI as a standard format shouldn't really differ across these distributions...

**Comment by shaunsingh** [comment]
I cannot find dvisvgm in either nix, arch, or the aur. I also would like to avoid running two tex distrobutions at once. Is there a recommend way to install, without having to install a seperate tex distribution?

**Comment by vlasakm** [comment]
On Arch Linux and IIRC other distributions, the TeX Live binaries are in a separate package, in Arch's case `texlive-bin` (70 MiB). You can get `dvipng` and `dvisvgm` there.

Disclaimer: I am not that familiar with these two utilities.

As their names hint, both programs use the TeX `.dvi` format. While XeTeX internally uses an extended version of the DVI format (`.xdv`), normally the user only sees the PDF which is automatically converted from `.xdv` with the use of `(x)dvipdfmx`. Tectonic also hides this intermediate step. You need to use `tectonic --outfmt xdv` to get the intermediate `.xdv` file.

But `dvipng` doesn't support this new version of DVI. And both utilities, if installed from the system, will not be able to find files from the tectonic bundles (i.e. fonts).

**Comment by pkgw** [comment]
Yes, if you need an honest-to-goodness classical DVI file, Tectonic won't work because it only produces the extended XDV format.

Depending on how the tools work, you might be able to fool them into using `pdftocairo`, which can convert PDFs to PNG, SVG, and other formats, or a similar tool — if I want to turn a TeX input into an image file output, that's my usual approach. Since the PDF is the (default) output of Tectonic in the similar way that a DVI file is the output of a classical (La)TeX engine, there might be some way to get the tools to transform the PDF instead of trying to transform a DVI.

**Comment by arcstur** [comment]
From the dvisvgm website, it supports `.xdv`
I've been using `pdftocairo` and it works great.

@pkgw how do you feel about including `dvisvgm` or other utilities in Tectonic? I'm using a python math engine (manim), and it uses `dvisvgm` to convert to svg, so I had to manually use `pdftocairo`. Maybe including `dvisvgm` in Tectonic would make it easier to replace texlive (which I don't know if is a goal of the project).

Or, maybe there could be a way to export a svg directly (instead of a pdf or xdv).

**Comment by shaunsingh** [comment]
I'm closing this issue because when I use XeLaTeX I have to use `xdvsvgm` and the enchanced `.xdv` format as well, so my issue its technically solved.

**Comment by pkgw** [comment]
@arcstur As a general principle, I'm a little on the fence. For both practical and aesthetic reasons, I don't think that it would be great to integrate every possible tool into Tectonic, and this particular case is *very* separable from the main operation of Tectonic (as demonstrated by the fact that `pdftocairo` does what is needed very effectively). On the other hand, it would be super awesome to have a command like `tectonic -X figure` or something that turned TeX into an SVG image in one shot.

One thought is that this is the sort of thing that Rust and Tectonic aim to make very easy: if there's a Rust crate that does PDF→SVG well, it shouldn't be too much code to create a project that connects it to Tectonic and does what's needed.

Then more specifically, there's the question of the complexity of the codebase in question. We can't practically integrate `biblatex` since it's a big Perl program. If `xdvsvgm` is a simple self-contained C-like program, it would at least be *possible* to integrate it into Tectonic; if it's Perl or Python, that wouldn't be an option at all.
