### ISSUE TITLE
cargo install fails due to libicuuc.so not found

### ISSUE THREAD

**Issue by wusatosi** [tectonic-typesetting/tectonic#829]
I am not experience with this matter but:
installing tectonic through `cargo install` (both `cargo install tectonic` and `cargo install --force tectonic --git https://github.com/tectonic-typesetting/tectonic.git`) does not work on my distribution (Ubuntu 21.04). 

The installation process successfully exited, however tectonic fails on initialization, even `tectonic --version` does not work. 

The temporary solution is to install `tectonic` through `brew`.

Related to: #138

**Comment by pkgw** [comment]
This can happen if you have multiple installations of the ICU libraries, and the build scripts find one version (using, e.g., `pkg-config`) but the Cargo build process creates binaries that find another. If you are using `brew`, you probably have ICU installed using `brew`, and in that case installing Tectonic using the same system is indeed the best way to go.

There are parts of this issue that Tectonic simply can't do anything about, but we might be able to get the build scripts to be able to detect when the produced binary will have this kind of issue.

To the best of my understanding, there isn't anything about this issue that's inherently tied to ICU, but ICU tends to expose it because the ABI version of its shared library (`libicuuc.so.XX`) changes frequently.
