### ISSUE TITLE
Cache index?

### ISSUE THREAD

**Issue by rekka** [tectonic-typesetting/tectonic#85]
I wonder if it would be possible/desirable to cache the index of the web bundle. 

Currently, tectonic seems to download the full index (`bundlename.index.gz`) whenever it encounters a file that is not in the local cache. It is rather big with 850kB. 

This is a bit annoying especially when the reason is a typo in the file name for the `\input` and `\includegraphics` commands. If the index were cached, tectonic could resolve this without touching the network. 

Added bonus would be that files in the bundle could be downloaded quicker.

**Comment by pkgw** [comment]
This is something to ponder. We need to be careful, though, since the bundle can change from one invocation to the next. So the program would need a way to check if the current bundle's SHA256 digest matches the one that the cached index corresponds to. But, right now the bundle SHA256 digest is found by reading a file named `SHA256SUM`, and if you can't be sure that your cached index is valid, the only way to correctly find that file is to download the index!

So I think that to solve this problem correctly, we will need to update the bundle storage format a bit. Which is definitely not a problem!

Neither Zip nor `tar` format is totally ideal for the bundle storage. Tar files don't (easily) let you compress files individually, which is important since we're downloading individual files within the archive in a random-access style. Neither format has an "index" that meets our needs; Zip files have the central directory, but it doesn't contain the offsets needed to start reading files automatically.

So you could imagine a custom archive format that had

- a header with the SHA256 digest that can be checked really easily
- an index
- the file data payload

We're not trying to invent a general-purpose file archive format, so using a specialized custom format doesn't seem like that silly of an idea.

**Comment by rekka** [comment]
I see, thanks. That sounds a bit complicated, and I have to admit I do not have much experience with efficient packaging.

Does SHA256 checksum need to be inside the bundle? The index itself is also a separate file.
