### ISSUE TITLE
\pdfoutput and hyperref compatibility

### ISSUE THREAD

**Issue by dkwo** [tectonic-typesetting/tectonic#863]
Is it expected that the example
```
\documentclass{article}
\pdfoutput=1
\usepackage{hyperref}
\begin{document}
Hello
\end{document}
```
fails on tectonic?
if I remove either \pdfoutput or hyperref then it works.
(It works fine with pdflatex (texlive), and it fails with xelatex (due to \pdfoutput=1).)

The error is
```
$ tectonic -X compile -p main.tex
note: "version 2" Tectonic command-line interface activated
Running TeX ...
(main.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06> (article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(size10.clo)) (hyperref.sty (ltxcmds.sty) (iftex.sty) (pdftexcmds.sty
(infwarerr.sty)) (keyval.sty) (kvsetkeys.sty) (kvdefinekeys.sty) (pdfescape.sty
) (hycolor.sty) (letltxmacro.sty) (auxhook.sty) (kvoptions.sty) (pd1enc.def)
(intcalc.sty) (etexcmds.sty) (url.sty) (bitset.sty (bigintcalc.sty))
(atbegshi.sty)) (hpdftex.def (atveryend.sty) (rerunfilecheck.sty
(uniquecounter.sty))) (l3backend-xdvipdfmx.def) (main.aux) (ts1cmr.fd)
(nameref.sty (refcount.sty) (gettitlestring.sty)) (main.out) (main.out)
error: main.tex:4: Undefined control sequence
! Undefined control sequence.
\PDF@SetupDoc ...pstringB {\@baseurl }\pdfcatalog
                                                  {/PageMode/\@pdfpagemode \...
l.4 \begin{document}

No pages of output.
Transcript written on main.log.
error: halted on potentially-recoverable error as specified
```

Thanks.

**Comment by vlasakm** [comment]
With normal XeTeX, it is an error to use `\pdfoutput`, as that is from `pdfTeX`.

Although for some reason in Tectonic `\pdfoutput` is defined since a4d78924d8f56fcd287701d7049845c7e14d8d8c.

It seems that by setting `\pdfoutput` to 1, something detects the used engine as pdfTeX and trouble ensues. But IMO mere presence of `\pdfoutput` could cause issues (if package would use its mere presence to detect pdfTeX). I don't know what was the initial reason for adding it @pkgw.

Note that you get PDF output automatically from Tectonic, without messing with low level stuff. How did you learn to use this command @dkwo?

**Comment by dkwo** [comment]
Right, I understand.
It is part of my standard latex template, as it was suggested by [arxiv](https://arxiv.org/help/submit_tex#pdflatex), but perhaps I can just drop it.

**Comment by vlasakm** [comment]
Well, if you compile a document with multiple engines (i.e with both pdfLaTeX for arxiv submissions and with XeLaTeX / Tectonic locally), then you should do the engine specific things conditionally. E.g.

```
\ifx\pdftexversion\undefined\else
  % do this if running under pdfTeX
  \pdfoutput=1
\fi
```

**Comment by dkwo** [comment]
The point of `\pdfoutput=1` is to tell arXiv to use pdflatex (instead of latex): if it is already runnig pdflatex, there's no point.
From Tectonic viewpoint, it should be harmless, not produce errors.

**Comment by vlasakm** [comment]
Actually, `\pdfoutput=1` is a very low level command of pdfTeX, that tells it to generate PDF instead of the TeX classic DVI format. When you run `pdflatex` it uses pdfTeX with `\pdfoutput=1` (PDF output) and when you  run `latex` it uses pdfTeX with `\pdfoutput=0` (DVI output, which can be converted to PDF e.g. with `dvipdfmx`).

So I presume that arxiv always runs `latex` but you can persuade it to be `pdflatex` by using this switch. But if they didn't always run pdfTeX, then such construct wouldn't work.

Because `\pdfoutput` it is a low level pdfTeX command it has no place in XeTeX (Tectonic), where the only possible output format is DVI (which is usually automatically postprocessed and converted to PDF with `xdvipdfmx`).

If your goal is to compile your document locally with Tectonic, and on arxiv which requires `\pdfoutput=1` for persuading its pdfTeX to generate PDF directly, instead of indirectly with postprocessing, then I think the snippet I shared above should be sufficient.

**Comment by dkwo** [comment]
I see, that makes sense.
Thank you.

**Comment by dkwo** [comment]
@vlasakm Since I've already abused your patience, do you spot any other package that should be removed or changed when using tectonic's fork of xetex?
```
\usepackage{microtype}
\usepackage{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{csquotes}
\usepackage{fullpage}
\usepackage{mathtools}
\usepackage{amsthm}
\usepackage{amssymb}
\usepackage{hyperref}
\usepackage{biblatex}
 \usepackage{cleveref}
\usepackage{authblk}
\usepackage{tabu}
\usepackage{tikz-cd}
```

**Comment by pkgw** [comment]
@dkwo You don't want that `fontenc` and `inputenc` packages — those aren't needed for XeTeX/Tectonic, which are Unicode-native. I don't think that `inputenc` will cause any problems, but font stuff should be done with `fontspec` rather than `fontenc`.
