### ISSUE TITLE
V2 layout and tools like latexdiff

### ISSUE THREAD

**Issue by clbarnes** [tectonic-typesetting/tectonic#876]
Many tools, including latexdiff, require you to point them at the root file of the document. As of the V2 recommended/ automatic layout, tectonic doesn't have one, and (presumably) implicitly concatenates the preamble, index, and postamble files. How can this be explained to tools which need a root file? What benefit does this layout provide if it is internal to tectonic and breaks all other latex workflows?

**Comment by pkgw** [comment]
I'll start with the very small-bore answer. One way to get this workflow to work in the V2 paradigm is to make `_preamble.tex` and `_postamble.tex` empty, and just put everything in `index.tex`.

In terms of how tools like `latexdiff` might be supported in the future while "leaning in" to the V2 paradigm, Tectonic might gain a mode similar to `latexpand` that would reduce the input file structure to a single homogenized text stream. The key thing here is that if/as document source structures gets more sophisticated (e.g. #872), Tectonic should really be the source of authority for how to resolve `\input` inclusions. Also, this mode would come with some guarantees about the superficial parse-ability of the input, which is kind of a tangent for this issue but is something I think is super important. (By "superficial" I mean that you can parse its syntax correctly without executing a full TeX engine, which is *impossible* in full generality.)

None of the above justifies the use of the V2 layout in the first place, though. I'll point you to [this comment][x] which attempts to explain the vision behind the V2 approach. In a certain sense I believe that it is best that V2 documents are *not* easily put into existing LaTeX workflows, because in some very profound ways the whole reason that Tectonic exists is that it is *not* going to be maximally compatible with the existing ecosystem.

As for the more specific motivation, I want to (1) encourage people to separate their setup code and actual document text, with a vision of (1b) potentially being able to parse and auto-format the different files in different styles appropriate for code and marked-up prose, and (2) open the window for Tectonic to automatically traverse and compile whole trees of input files without needing explicit `\input` statements, which is a more natural fit for web-based outputs and I believe will open up some major usability wins for certain document types.

[x]: https://github.com/tectonic-typesetting/tectonic/issues/846#issuecomment-985576778

**Comment by clbarnes** [comment]
Thanks, this makes sense! There's a lot wrong with the whole *TeX ecosystem and making groundbreaking improvements is a big and bold goal. For me, the big doc I'm working on at the moment (and the smaller docs I work on more regularly) are dependent on latexdiff, texcount etc., so I have gone with the V1 interface and a "standard" structure, but personally separate the preamble and prose for exactly the reasons you describe (they're just `\input` into the index .tex file).

**Comment by pkgw** [comment]
I'm glad that Tectonic is still managing to meet your needs! I'm always torn since Tectonic really needs a huge injection of developer effort to make good on its more visionary ideas, but I think those ideas are worth pursuing even if the current status can get a little awkward.

I'm going to close this issue for bookkeeping, but additional comments are certainly welcome! I'm also about to turn on the GitHub Forum support, which will hopefully provide a better venue for this sort of discussion.

**Comment by zzamboni** [comment]
Another way of having a single "root" document (or a single self-contained document) while preserving the Tectonic structure is to disable preamble and postamble in `Tectonic.toml` like this:
```
[[output]]
name = 'something'
type = 'pdf'
index = 'something.tex'
preamble = ''
postamble = ''
```
This allows you to remove `_preamble.tex` and `_postamble.tex` without Tectonic complaining 😄
