### ISSUE TITLE
Can't run `tectonic -X new` because of 307 temporary redirect

### ISSUE THREAD

**Issue by azerupi** [tectonic-typesetting/tectonic#887]
I'm currently unable to create a new tectonic document due to a temporary redirect.

```
$ tectonic -X new test-document
note: "version 2" Tectonic command-line interface activated
note: creating new document in directory `test-document`
note: connecting to https://archive.org/services/purl/net/pkgwpub/tectonic-default
error: failed to create the new Tectonic workspace
caused by: unexpected HTTP response code 307 Temporary Redirect for URL https://archive.org/services/purl/net/pkgwpub/tectonic-default
```

The resource is still accessible behind the redirect so maybe tectonic should follow the redirect to be more reliable?

**Comment by pkgw** [comment]
You must be running an older version of Tectonic, because you're seeing the symptoms of a fairly major breaking change introduced by Archive.org: see [the release notes for version 0.8.0][rl]. If you update to a newer version, your problem should be fixed.

[rl]: https://github.com/tectonic-typesetting/tectonic/releases/tag/tectonic%400.8.0

I'm going to close this issue since I think that's all there is to it, but please comment or file a new issue if there's more to discuss!

**Comment by azerupi** [comment]
Oh my bad. I'm really sorry for the noise!
Thank you for the quick reply and for tectonic, it is a joy to use :slightly_smiling_face:
