### ISSUE TITLE
Synctex with `build` ?

### ISSUE THREAD

**Issue by sneakers-the-rat** [tectonic-typesetting/tectonic#889]
I am noticing that there is a synctex flag for the `compile` command but not for the `build` command, when I try it I get: `error: Found argument '--synctex' which wasn't expected, or isn't valid in this context`. I'm wondering why this is the case? Am i correct in thinking that `build` is the intended "canonical" mode of use? If there aren't any reasons aside from time, I'm still learning Rust but I would be willing to try and PR if you give me a rough pointer towards what would need to change. Thanks!!! love tectonic!!!

(using version 0.8.2)

edit: `\synctex=1`  in the preamble seems to work. Seems like this should be in the docs, even though it's a TeX feature rather than a tectonic feature, since there is a `--synctex` flag for the `compile` command and not `build` i think it would be worth a quick note in the docs/book <3 feel free to close this.

**Comment by pkgw** [comment]
Thanks for inquiring! The idea is that for Tectonic documents (i.e., the V2 interface and `build` command), Synctex would be turned on by activating some kind of key in the `Tectonic.toml` file, or `\synctex=1`, rather than a command-line argument. It seems like Synctex should be more of a "set it and forget it" kind of option (saved in the TOML file) rather than something that people are going to want to choose whether they turn it on and off from one build to the next ... although maybe I'm just suffering from a failure of imagination here.

Anyway, that being said, I haven't implemented such an option in the `Tectonic.toml` file, since I don't use it myself and I've thought that it would be a nice project to leave for new contributors. That could definitely be you! I think that it should be *relatively* easy to implement:

- Declare a new option in the `docmodel` crate as an `OutputProfile` setting
- Document it
- Wire in the main `tectonic` crate to respect the option
- Write a few tests

**Comment by sneakers-the-rat** [comment]
omg i am excited, this will be my first Rust outside of tutorials!

**Comment by pkgw** [comment]
Great! Tectonic is a complicated piece of software so there will probably be some pieces that become a bit of a slog, but I am happy to assist as best I can. The first step, if you haven't done it yet, is to get it all compiling from source on your own machine. Since there are some external dependencies, that can be a bit of a more annoying process than it is for some Rust programs.

**Comment by S1M0N38** [comment]
Is there some progress? I'm also interested in this option and here is why.

I write tex file using Neovim with the help of [texlab](https://github.com/latex-lsp/texlab). On file save LSP trigger the whole project compilation (it execute `tectonic -X build  --keep-intermediates --keep-logs`) producing _./build/default/default.pdf_. However is impossible to implement forward and backward search without **SyncTeX** data.

The workaround is to put all in the _index.tex_ and use `tectonic -X compile index.tex --synctex --keep-logs --keep-intermediates` for compilation. This produce  SyncTeX data and allow the usage of forward and backward search.
This solution is suboptimal because I cannot longer use the neat partition __preamble_ / _index_ / __postable_. Moreover with `built` I can trigger the compilation from every Neovim buffer because all compilation directive depends on _Tectonic.toml_.

**Comment by sneakers-the-rat** [comment]
I haven't had time to do this yet, but putting `\synctex=1` in my preamble worked, and created synctex hooks for forward/backward sync.

**Comment by rm-dr** [comment]
Do we really want synctex options to be in the document?
As far as I've seen, synctex is only used when editing the document, to make preview navigation easier. The final version of a doc never includes synctex files.

I think it makes more sense to have a command-line option for this, much like ``--keep-intermediate``. This allows for easy integration into editor build scripts.

**Comment by lnay** [comment]
I personally agree with @rm-dr on this, that it should also be possible to enable synctex from a cli flag.

While I'm all for housing project metadata in a config file, I would say whether or not to use synctex is not really project metadata; it's more of a personal dev tool because:
- It does not affect the build of the actual document
- It is never necessary in final/CI builds of the document
- The choice to use it likely depends on the author's personal tools and different authors on the same project may not all use it

Context: I have not used tectonic in my own projects (but am a big fan of synctex in multi-file projects). I have only tried tectonic recently following an issue raised on the LaTeX extension for the Zed editor. I'm also considering what integrations with this extension could look like.

@pkgw I could work on adding the CLI flag provided the maintainers are open to this feature.

**Comment by koushikkhan** [comment]
> I haven't had time to do this yet, but putting `\synctex=1` in my preamble worked, and created synctex hooks for forward/backward sync.

This works for me as well.
