### ISSUE TITLE
this project should be sponsorable

### ISSUE THREAD

**Issue by stumash** [tectonic-typesetting/tectonic#913]
take my money!

**Comment by pkgw** [comment]
Thank you, I definitely appreciate the sentiment! Speaking just for myself, the nature of [my day job][me] is such that, for better or for worse, accepting sponsorship wouldn't actually enable me to spend any more time on the project. Honestly, taking people's money would probably be a net *loss* since I'd have the same amount of time to spend, but I'd feel guiltier about everything that I'm not doing.

[me]: https://newton.cx/~peter/about-me/

I am more than happy to enable sponsorship of the project to support other people's work, but I'm not aware of any clear opportunities for that at the moment. One specific possibility: a couple of times in the past, I've investigated paying a graphic designer to design a nice project logo, but have never been able to find someone able to commit to a project, even with payment.

**Comment by stumash** [comment]
I get where you're coming from, and I appreciate the high ethical standard you're holding your self to ❤️ 👍 

however, I do think that there's a certain intrinsic motivation and prestige to actually being paid, even if it's severely underpaid, for open source contributions. I think a lot of coders would be more motivated to work on open source stuff even for small amounts of money. I think it significantly increases the 'legitimacy' of the work.

I really wish github would let people crowdfund certain issues on repositories, kind of like bug bounties at major corporations.

okay rant over. love the project! don't feel obliged to add any sponsorship or anything! cheers
