### ISSUE TITLE
Can halt_on_error be disabled?

### ISSUE THREAD

**Issue by jooooscha** [tectonic-typesetting/tectonic#916]
I have a document which causes 
```
Running TeX ...
error: pdflscape.sty:105: Package pdflscape Error: The driver option `' is not compatible
(pdflscape)                with XeTeX, using driver for XeTeX (dvipdfm) instead.

See the pdflscape package documentation for explanation.
Type  H <return>  for immediate help
error: halted on potentially-recoverable error as specified
```
when compiled with tectonic.

Assuming the error is, indeed, recoverable I dug around in the code and found the *message* to be caused by the `halt_on_error` variable in the `TexEngine` struct.
I see that it is set to false in some tests but I did not found out how to disable this for compiling.

Did I miss something?
How can I specify that I do not want to halt on `potentially-recoverable` errors?

Thanks in advance

**Comment by pkgw** [comment]
Yes, there's an "unstable option" `-Z continue-on-errors` that should do what you want. It's mentioned here in the documentation although I'll admit that it's not super easy to find:

https://tectonic-typesetting.github.io/book/latest/v2cli/compile.html#unstable-options

**Comment by jooooscha** [comment]
Ah, yes. Thank you, I did miss that. 

However, enabling this does not seem to change anything. I get the same error. I tried `tectonic file.tex -Z continue-on-errors` and a bunch of other permutations. I also tried the V2 interface.
Anything I could have missed? 

I am sorry, if this is a dump mistake.

For the record, I am on version 0.9.0.

**Comment by pkgw** [comment]
That's odd. Maybe I'm overlooking something simple here. Would you mind providing a minimal example document that fails for you?

**Comment by jooooscha** [comment]
Umm, that could actually take a while. 
The document is based on a huge template I have to use.

I will investigate what's causing the error and come back to you.

Thanks, anyway, for you time :)

**Comment by jooooscha** [comment]
Ok, I am not sure this is helpful, but this is the smallest example I get the same error.

```
\documentclass{article}

\usepackage{pdfpages}
\pdfoutput=1

\begin{document}
Hello World.
\end{document}
```

Again the `-Z continue-on-errors` option does not seem to change.

If this does not help, I accept that the template will not work with tectonic, If I remove the `\pdfoutput=1` in the template some other control sequence is not found. Debugging that could take for ever 😅

**Comment by vlasakm** [comment]
I think your issue with `\pdfoutput` is very similar to https://github.com/tectonic-typesetting/tectonic/issues/863. I think the same solution I propose there could work for you.

If you locally compile with Tectonic / XeTeX / LuaTeX, and someone else might compile it with pdfTeX, you can have something like the following, inspired by [iftex documenatation](https://www.ctan.org/pkg/iftex)

```tex
\usepackage{iftex}
\iftutex
  % running under Unicode TeX engine (XeTeX, LuaTeX), use modern things
  \usepackage{fontspec}
  \setmainfont{TeX Gyre Termes}
  \usepackage{unicode-math}
  \setmathfont{Stix Two Math}
\else
  % running under old (pdf)TeX 
  \usepackage{newtxtext,newtxmath}
  % uncomment the following line to make arxiv's setup generate PDF output
  %\pdfoutput=1
\fi
```

If, as you say, leaving out `\pdfoutput=1` doesn't work for your template, please share more information about the template as well as your command line output and log file (`tectonic --print --keep-logs input.tex`). I am speaking entirely from my perspective but I would expect Tectonic to behave like `xetex` from TeX Live, thus if you see same error there, it is most likely not a Tectonic issue (e.g. your problem like parly here, is a discrepancy between `pdftex` and `xetex`), you cannot expect Tectonic to behave like pdfTeX. (Though this is probably not true, since I vaguely remember an effort to compile all of arxiv with Tectonic, and that AFAIK wouldn't work with XeTeX.)

But as you can see these types of engine specific checks in _your_ preamble should mostly concern Unicode or fonts, because for other things the autodetection for backend in XeTeX is usually pretty good, so prefer to not "hardcode" anything. If you do, prefer options like `xetex`, `dvipdfmx` or `dvipdfm` which is what is actually used in Tectonic.

For your simplified case, this compiles just fine (and the `pdfpages` works as expected):

```latex
\documentclass{article}

\usepackage{pdfpages}

\begin{document}
Hello World.

\includepdf[pages={1}]{other.pdf}

\end{document}
```

To elaborate on the issue:

Some packages need to do things differently for each TeX engine (TeX, pdfTeX, XeTeX, LuaTeX) or the used "backend" (the part of TeX pipeline that converts TeX internal structures to your desired format, such as PDF).

Different TeX compilation pipelines use different engines and backends, this can give quite a few combinations, e.g.:

```
.tex -> (TeX) -> .dvi
.tex -> (TeX) -> .dvi -> (dvips) -> .ps
.tex -> (TeX) -> .dvi -> (dvips) -> .ps -> (ps2pdf) -> .pdf
.tex -> (TeX) -> .dvi -> (dvipdfmx) -> .pdf
.tex -> (pdfTeX with \pdfoutput=0) -> .dvi
.tex -> (pdfTeX with \pdfoutput=1) -> .pdf
.tex -> (XeTeX) -> .dvi -> (xdvipdfmx) -> .pdf
```

The last one is what Tectonic does, because it in a sense is mostly XeTeX under the hood. The `.dvi` to `.pdf` step is done behind the scenes. As you can see, XeTeX doesn't itself listen to `\pdfoutput`, because it can never produce `.pdf` directly, unlike pdfTeX, which can produce `.dvi` or `.pdf` directly.

_But_ some packages use the mere presence of `\pdfoutput` and its value to sniff around and try to tell which pipeline you are using. Sometimes this is impossible to do and you need to specify that manually (especially when going through `.dvi`, because there is no way to tell beforehand what you are going to do with the `.dvi` file - convert it to PostScript or PDF?
(This matters for example with the famous TikZ package which embeds images in `.dvi` in the desired output format (PostScript ord PDF) and hence needs to know beforehand what you intend to do with your `.dvi` file.)

Hence I think that Tectonic should never have defined `\pdfoutput` in the first place. Though there may be a reason I don't know.

When you then say `\pdfoutput=1` and don't tell the `pdfpages` package your backend manually, it autodetects it to `xetex`, this is still fine. But it loads `pdflscape` package, which uses the `\ifpdf` command from `iftex` package to detect it, normally, this `\ifpdf` should be false for XeTeX, but it is not here, because of `\pdfoutput=1`. Thus first `pdflscape` sets the backend to be `pdftex` (which wouldn't work since `pdftex` is not used!), but because of the logic in the code then tries to also detect `xetex`. It detects it, but sees that there is already a backend set (`pdftex`), but these are incompatible, thus the raised error you see. Because of the weird sitaution the error message is also a bit weird.

@pkgw Do you remember the reason for adding `\pdfoutuput`? Can the issue be sorted in other way?

**Comment by vlasakm** [comment]
As for the `halt_on_error`: the error is indeed recoverable in this case. But the actual effect of the `continue-on-errors` option probably got lost in refactoring.

The following seems to work:


```diff
diff --git a/src/driver.rs b/src/driver.rs
index a0e2bdf6..2d20f465 100644
--- a/src/driver.rs
+++ b/src/driver.rs
@@ -1780,7 +1780,7 @@ impl ProcessingSession {
                 CoreBridgeLauncher::new_with_security(&mut self.bs, status, self.security.clone());

             TexEngine::default()
-                .halt_on_error_mode(true)
+                .halt_on_error_mode(!self.unstables.continue_on_errors)
                 .initex_mode(self.output_format == OutputFormat::Format)
                 .synctex(self.synctex_enabled)
                 .semantic_pagination(self.output_format == OutputFormat::Html)
```

**Comment by pkgw** [comment]
@vlasakm Well that seems like a likely issue! If you'd like to get the credit for the fix by filing a pull request, please do that. Or I can put the patch in myself if you don't have the time.

**Comment by jooooscha** [comment]
Wow @vlasakm. Thank you for this detailed answer. This will help me a lot adapting the template to work with tectonic.

I am glad my issue still did some use to the project. Thank you all for your time, help, and this very nice project.
