### ISSUE TITLE
Bundle download failing due to HTTP redirect

### ISSUE THREAD

**Issue by seabass-labrax** [tectonic-typesetting/tectonic#932]
Running the command:

``` bash
tectonic -X compile name-of-document.latex
```
...results in this error:
``` text
note: "version 2" Tectonic command-line interface activated
note: connecting to https://archive.org/services/purl/net/pkgwpub/tectonic-default
error: couldn't probe
caused by: unexpected HTTP response to URL https://archive.org/services/purl/net/pkgwpub/tectonic-default: 307 Temporary Redirect
```

It seems like Tectonic is unable to follow the HTTP redirect that archive.org sends back from Tectonic's request, causing any command to fail (unless the bundle is already cached, I would presume).

I'm running Tectonic 0.4.1, installed with Nix from the `docker.io/nixos/nix` container image (hash `sha256:858f475577cfcf1881e69adc58cf34e4a28c6d40835fd89edd3a05aa72e86012`). The command that I ran to start the container is `docker run -i -it -v $PWD:/p -w /p docker.io/nixos/nix`, and that's on Docker version `20.10.5+dfsg1` from Debian 11.

**Comment by pkgw** [comment]
You're running into an issue that cropped up last year and was fixed in [tectonic 0.8.0][1], which had to introduce a new URL redirection service. If you upgrade to a newer release, your problem should go away.

[1]: https://github.com/tectonic-typesetting/tectonic/releases/tag/tectonic%400.8.0

I'm going to close this issue because it seems pretty clearly to correspond to a problem that's been addressed on Tectonic's side, but I'm happy to follow up if you have any further questions or comments.
