### ISSUE TITLE
Mirroring the tectonic bundles

### ISSUE THREAD

**Issue by PhotonQuantum** [tectonic-typesetting/tectonic#948]
I want to provide a mirror of tectonic bundles at my university. Is there a suggested way to mirror the tectonic bundle?

Currently, the fallback bundle is served at `https://relay.fullyjustified.net/default_bundle_v33.tar`, and this URL redirects to `https://data1.fullyjustified.net/tlextras-2022.0r0.tar`. 

It's possible to mirror the bundles by downloading them from the URLs, but it would be nice if a rsync or similar method is available.

**Comment by pkgw** [comment]
Sorry for the slow reply! Currently the recommended method would be to just download the whole file (and the paired `.index.gz` one as well). The bundles are immutable once published so rsync shouldn't really provide any benefits. Also, the bundle is a few gigabytes but not *many* gigabytes, so if you're on a modern internet connection it should be a pretty manageable download.

**Comment by PhotonQuantum** [comment]
Thanks! In that case, it will be helpful if there's a directory index (i.e., no need to guess the filename of all the bundle files).

**Comment by pkgw** [comment]
Since the files are served off of an Azure static website service, I think that it might not be possible to have directory indexes. But there is a file associated with the redirection service that will build up a list of the different released bundles:

https://github.com/tectonic-typesetting/tectonic-relay-service/blob/main/temporary_redirects.map

**Comment by PhotonQuantum** [comment]
The given link is quite helpful!  As my problem has been resolved, I'm closing this issue.
