### ISSUE TITLE
tectonic 0.11.0 generating html fails

### ISSUE THREAD

**Issue by ville-h** [tectonic-typesetting/tectonic#954]
using tectonic 0.11.0 I was trying to generate html from:
```
\documentclass{article}
\begin{document}
    xxx
\end{document}
```
with the command: `tectonic --outdir build --outfmt html src/xxx.tex`, but it errors out with:
```
Running spx2html ...
warning: imbalanced tags; had to close 0 to find `div`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/engine_spx2html/src/lib.rs:1660:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Generating a pdf works fine.

**Comment by pkgw** [comment]
Well that's embarrassing! You should know that as things currently stand, a great deal of special options are needed to get HTML output (I should probably add a warning), but we certainly shouldn't panic.

**Comment by ville-h** [comment]
I did have a look at the commit, but based on [the message](https://github.com/pkgw/tectonic/commit/462bb92cb9536daf6776227bc2cab5214b111974#diff-86eb9aca9675a44d1e7afd0ad70f4664fbe2ec8e7de58b9d413bc3a897bdf460R1988) I wouldn't know what to do. The word `template` appears to be key, but how do I specify one? What does it mean concretely to be "html-compatible"? The comment above doesn't make the steps I need to take any more concrete either. I thought tectonic was supposed to download everything as-needed?

**Comment by pkgw** [comment]
Those are all good questions. I think that, unfortunately, there's just too much context to pack into one error message, and what you read is the best I could come up with.

The longer explanation is that producing HTML requires the engine, the TeX code, and HTML/JS/CSS templates that all work together. The engine has core support, which you can turn on with the `--outfmt` option, but right now the only existing example of the "full stack" is the specialized [tt-weave] framework that produces [XeTeX: A Pseudoprogram][xap]. So I'm afraid that the `--outfmt` option is more or less useless unless one is willing to read the HTML output code to understand the various `\special`s and then write some TeX, HTML, CSS, and JS that stitches everything together. The vision is that one day we'll include all of the necessary templates and customizations to the standard document classes and packages so that what you've attempted will Just Work, but sadly that's still far off. My plan is to shake down the details with specialized cases like [XAP][xap] and build up the "transparent" support as we better understand the problem space.

[tt-weave]: https://github.com/tectonic-typesetting/tt-weave/
[xap]: https://stacks.fullyjustified.net/xap/2022.0/

**Comment by ville-h** [comment]
Ok, fair enough. For my particular use I was mostly interested to see how mathematical formulas would turn out in MathML. I mention it just in case that once it's time to work on html support it would be considered. Thanks.

**Comment by pkgw** [comment]
Sorry that we're not quite there yet, but thanks for giving it a shot!

There are some issues raised in this ... issue ... that merit further investigation, namely how we give users a realistic expectation of where the HTML output is at right now. But to keep things tidy I'm going to go ahead and close this; I tend to think that those should be explored in new GitHub issues, although additional comments here are definitely OK.
