### ISSUE TITLE
Specify output path

### ISSUE THREAD

**Issue by h4llow3En** [tectonic-typesetting/tectonic#96]
Unless tectonic writes the resulting file in the input file directory there should be a possibility to specify an output path (and default could be probably `.`)

**Comment by pkgw** [comment]
As of b629285, Tectonic will create the output file(s) in the same directory as the input by default. Do you think it would still be useful to have an option to override the output directory?

**Comment by rekka** [comment]
I agree that this would be quite useful for certain kinds of workflows.

**Comment by h4llow3En** [comment]
I think you could add a `-o, --output` to the accepted arguments. If you wish I could make a PR out of it.

**Comment by pkgw** [comment]
Yes, I tend to think that this would be a useful feature to have.

The implementation should be pretty straightforward, I think. You'd add a `PathBuf` field to the `ProcessingSession` struct in `cli_driver.rs` that stores the output directory. It would default to the directory containing the source files (or `.` for input on stdin), but could be overridden with a `-o` option if provided. I think I'd rather have the long name of the option be `--outdir` rather than `--output`, though.

**Comment by h4llow3En** [comment]
Alright, i will work on this and make a PR

**Comment by h4llow3En** [comment]
Is it really necessary to add a new field? If I understand the current use of `fs_root` right, it does only provide the path to create `real_path` [here](https://github.com/tectonic-typesetting/tectonic/blob/master/src/cli_driver.rs#L636).
