### ISSUE TITLE
PlantUML

### ISSUE THREAD

**Issue by JanValiska** [tectonic-typesetting/tectonic#973]
Hi, thanks for awesome work.
I'm just curious if I can somehow solve problem with PlantUML tex module.
I'm trying compile simple document like:
```
\documentclass{article}
\usepackage{plantuml}
\begin{document}
\begin{plantuml}
  @startuml
  Alice -> Bob: Hello
  Alice <- Bob: Hi!
  @enduml
\end{plantuml}
\end{document}
```

but the result of `tectonic -X watch` command is:
```
note: "version 2" Tectonic command-line interface activated
[Running `tectonic -X build`]
note: "version 2" Tectonic command-line interface activated
Running TeX ...
error: plantuml.sty:57: ! LaTeX Error: File `pythontex.sty' not found.
error: halted on potentially-recoverable error as specified
```

Is it possible to include `pythontex.sty` in Tectonic? Or is there another way to install that dependency?
Thank you.

**Comment by pkgw** [comment]
Apologies for taking a *very* long time to follow up this question.

The dependency on pythontex looks like one that would be relatively tricky to integrate, since it seems like it requires custom modules to be installed with one's Python interpreter. If you can get those modules installed with your system Python, you might just need to drop the `pythontex.sty` file alongside your TeX source. You'd then need to make sure to build your document with shell-escape enabled. Tectonic's shell-escape support tries hard to maintain encapsulation of its operations (to promote reproducibility), and sometimes that can cause problems for certain modules. But hopefully if you can get those pieces in place, the shell-escape processing will work here. If you get that far it would be valuable to hear back about whether it works or not!

**Comment by RaafatTurki** [comment]
any update?

**Comment by rm-dr** [comment]
The pythontex issue has been fixed, but tectonic still won't compile PlantUML. Here's why:

- PlantUML's [ctan package](https://ctan.org/pkg/plantuml) states that it only runs on LuaLaTeX. This cannot run in Tectonic, since we don't run lua.
- PlantUML also depends on pythontex, which requires an external command (python) and thus also doesn't work with tectonic.
