### ISSUE TITLE
ToC not rendered when -r 0 and -o are used

### ISSUE THREAD

**Issue by vojtechkral** [tectonic-typesetting/tectonic#981]
Hi.
When tectonic is called as

    tectonic -r 0 -o out texfile.tex

Tectonic won't render the ToC pages... most of the time. A moment ago I got it render ToC pages from a `.toc` file next to the `texfile.tex` (rather than the `out` directory, which is strange) but I can't seem to get it to do that again. I wonder if timestamps are somehow factored in? It's quite strange.

This only happens when both `-r 0` and `-o` are used.

---

NB. I need to use `-r 0` because I need to customize the `.toc` file between LaTeX runs. This seems to be the only way to get an alphabetically sorted ToC. Edit: Looks like I can't use `--pass tex` either, because that doesn't generate a PDF file.

**Comment by vojtechkral** [comment]
I found out I can work around this like this:
1. Run the first pass with `-o`
2. Read the list of intermediate files from the output dir and memorize the filenames.
3. Copy those intermediate files next to the input `.tex` file.
4. Run the second pass _without_ `-o`.
5. Remove the intermediate files.

This seems to work but it's a bit hacky.

**Comment by vlasakm** [comment]
I don't know much about Tectonic's file searching and didn't look. But it seems that the output directory is not included in search paths, so the `.toc` file cannot be found, thus no table of contents is produced. `-Z search-path` can help with that. Also since you seem to be editing the file in between runs, you seem to be missing `--keep-intermediates`.

```latex
\documentclass{article}

\begin{document}

\tableofcontents

\clearpage

\section{a}
\subsection{b}
\section{c}

\end{document}
```

```bash
tectonic -r 0 -o out --keep-intermediates -Z search-path=out texfile.tex
```

In case this is not what you mean, please provide a [MWE](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) and the exact sequence of commands you run.

I don't know whether the fact that outdir is not searched by default is intentional or not.

**Comment by vojtechkral** [comment]
Hi, thanks for the reply.

Yes, I am using `-k` as well.

> But it seems that the output directory is not included in search paths, so the `.toc` file cannot be found, thus no table of contents is produced. `-Z search-path` can help with that.

Yup, that seems to fix it, thanks!

> I don't know whether the fact that outdir is not searched by default is intentional or not.

It seems like a bug to me. Also, if the outdir is not searched, why is the ToC rendered correctly with `-r 1`?

**Comment by vlasakm** [comment]
> > I don't know whether the fact that outdir is not searched by default is intentional or not.
> 
> It seems like a bug to me. Also, if the outdir is not searched, why is the ToC rendered correctly with `-r 1`?

I suppose that Tectonic has special bookkeeping for intermediate files (I vaguely remember there being a temporary directory for each run?). So if Tectonic does all the passes in one invocation of the `tectonic` binary, then it has the intermediate files somewhere where it can find them. On the other hand, if `-r 0` is used, the second run has clean slate with regards to intermediate file bookkeeping and the ordinary file search fails, because `outdir` is not in search paths.

**Comment by pkgw** [comment]
Thanks for following this up, @vlasakm.

It is very intentional that the output directory is not searched for input files by default. If you don't do this, you can't have reliable and repeatable builds because there's no way to know that you're not injecting circular dependencies. Think of something like a C or Rust compiler — having the build output potentially depend on itself would lead to all sorts of non-reproducible behavior. Tectonic's built-in support for looping and handling intermediate files basically tries to encapsulate the looping behavior that LaTeX processing requires, so that higher-level build tools can operate in a non-cyclical way.

Anyway, I have similar use cases where I have external tools that customize intermediate files — in particular, I generate custom `.bib` files based on the `.aux` output. My workflow is as follows:

1. The first pass has options like:
  - `--pass aux` to generate aux file and related intermediates
  - potentially `--keep-intermediates`
  - `--hide $INTERMEDIATE` for all of the intermediates to make sure this pass always acts as if pristine
  - `--makefile-rules` because I drive from [Ninja], which can use the emitted file to learn deps
2. Then my tool does whatever processing it needs to emit a corrected/etc intermediate file in the source directory
3. The second pass has options like:
  - It uses the default PDF pass to finish the compilation
  - Potentially `--hide` arguments for non-customized intermediates that should be ignored
  - `--makefile-rules` again for Ninja's dependency-tracking

So I think the secret sauce here is the `--hide` option, which can let you update an intermediate-like file in the source directory while making sure that the first pass always acts as if pristine. If your source directory is read-only, you can tweak things to emit your customized file into a writable work directory and tell Tectonic to find it with a `search-path` option.

[Ninja]: https://ninja-build.org/

**Comment by vojtechkral** [comment]
> It is very intentional that the output directory is not searched for input files by default. If you don't do this, you can't have reliable and repeatable builds because there's no way to know that you're not injecting circular dependencies. Think of something like a C or Rust compiler — having the build output potentially depend on itself would lead to all sorts of non-reproducible behavior. Tectonic's built-in support for looping and handling intermediate files basically tries to encapsulate the looping behavior that LaTeX processing requires, so that higher-level build tools can operate in a non-cyclical way.

Ok, but why isn't this a problem without `-o` as well? That's what's puzzling me, I would expect `-o` to simply just change location of files, but not build process semantics. But I don't claim to understand LaTeX build process very well...

**Comment by pkgw** [comment]
@vojtechkral If I'm understanding the question correctly — it's because without `-o`, the output directory is the same place as the input directory. In that case, Tectonic doesn't have the information needed to "boot up" the compilation without paying attention to preexisting build outputs — that's what the `--hide` option is for. This is one reason that the V2 approach defaults to placing build outputs in a separate `build/` tree.

**Comment by vojtechkral** [comment]
@pkgw Ok, thanks. Since this is not a bug them I'm closing this issue...
