### ISSUE TITLE
Stabilize search-path in V2 CLI

### ISSUE THREAD

**Issue by vojtechkral** [tectonic-typesetting/tectonic#984]
This is followup from #981 - since I am now relying on `search-path`, It would be nice if it could become a stable option (in the V2 interface, I presume).

Related to this, since I am calling `tectonic` from another tool in an automated way, it would be great if my tool could tell what CLI interface a supplied tectonic binary supports.

**Comment by pkgw** [comment]
@vojtechkral I'm not sure if I understand the second part of your request — you want your tool to be able to probe the CLI interface provided by Tectonic? I think the most straightforward way to do that is going to be running `tectonic --version` and activating various features based on when they were added.

**Comment by vojtechkral** [comment]
@pkgw Ok, that could be done, yes

**Comment by pkgw** [comment]
As for the second part, since the search path is part of the build specification, in the V2 document model it should really go into the `Tectonic.toml` file rather than be given on the command line. The goal is that `tectonic build` should always do the right thing without needing any additional arguments.

The status of this feature is basically as I recently commented in https://github.com/tectonic-typesetting/tectonic/issues/985#issuecomment-1403025872 : the basic idea is there but someone needs to sit down and write the code to implement it. I'm afraid that my priorities have been on HTML support lately, so I haven't been able to make progress on it personally, but I am more than happy to help work with someone else to implement it.
